export default [
  {
    uuid: "052b1ef1-aba6-4072-b133-cd6078966afc",
    game: "categories",
    pack: "boysnight",
    prompt: "energy drinks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "07439784-75d0-4a8a-ab68-6d69e54ec080",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have a one night stand",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "07f1ce70-330c-4c40-8c97-2b6471a40bc6",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you see a girl drop her folder and her papers go everywhere",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "0e9bbeab-58c2-4ff8-a0e9-fceb2c6c13b7",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "has the hottest girlfriend",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "11af8277-a5f2-44ae-ba06-552db51e6e22",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: 'said "im not racist, but..."',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "14119837-c098-4e4c-995a-045f40f80a0d",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "tell you they've just been grinding",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "14c32d0b-44af-4d74-9ce8-deebca92d3b5",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if you've ever gotten whiskey dick",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "for each time,",
    sipFlag: -1,
  },
  {
    uuid: "14e0bbd2-5937-4d52-84de-14547c53362b",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: 'search "granny" on a porn site',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "19542f8a-caa8-4745-85fb-19187495c8d3",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "be a dirty cop",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "1b661080-302a-4c18-a6fe-68cf5ec8e005",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "win a beer pong tournamnet",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "1daa0437-bcd9-43aa-a5cb-c5ba1e22fa78",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have atheltes foot",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "1e3a01f5-ca3e-4179-82f6-4c11003b5148",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: " to have grindr installed",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "21272cd6-7a58-4388-8653-a63cbc107c1a",
    game: "wildcard",
    pack: "boysnight",
    prompt: "see who can hold their breath the longest",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "largest lungs",
    sipFlag: -3,
  },
  {
    uuid: "2127fa70-39d8-43ad-ae1c-783e7db82118",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "use dude as a question and statement",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "24ee63db-d90b-4383-b7ca-18ad44739726",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "who is the most athletic",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "25339c05-fb85-4981-a782-5557d064f915",
    game: "wildcard",
    pack: "boysnight",
    prompt: "explain to the boys what the vulva is",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "they decide,",
    sipFlag: 1,
  },
  {
    uuid: "25c0306a-0dda-4708-977b-80016e9f3806",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "red bull or monster",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "26b24e6e-a1dd-4689-b870-bbadb2421297",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get caught flexing in the mirror",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2743b16a-bdb1-4ddf-9c92-09405e6aa571",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "been queefed on",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2754c77f-c741-435e-aafe-ea922a5e4a09",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: " to bail on plans",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "27d37d5c-21c6-4db5-b971-73c122cb9318",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "give sex advice to a bro",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "28249982-1075-407f-8675-38fba9e3dfc7",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "to puke and rally",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "291ad0fb-8e27-4a72-9438-01134a434ebf",
    game: "wildcard",
    pack: "boysnight",
    prompt: "are you are the ugly one in your relationship",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if yes,",
    sipFlag: 1,
  },
  {
    uuid: "29289d79-8320-487e-93d9-252f5b165693",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have a hit list",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2a18dab9-f2c3-4517-92de-98f9dd056ff0",
    game: "wildcard",
    pack: "boysnight",
    prompt: " (touch your nose)",
    header: "NOSE GOES",
    cardType: "GROUP",
    drinkHeader: "last person,",
    sipFlag: 1,
  },
  {
    uuid: "2ccaaa24-bf14-412d-9d4f-84f4eee197a6",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "the last ph video you watched pops up on your phone while getting a girl's number",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "2d15b6e5-6244-477c-8b97-81f94d7fadb9",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "hit on a girl who was underage",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2e7d7a13-087e-40ce-bea4-de3d76e89b59",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you got injured playing intermural flag football and the nurse is hot",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "2eaa3485-d97d-4763-a87b-1ddc244419a0",
    game: "wildcard",
    pack: "boysnight",
    prompt: 'who uses the term "alpha male" most',
    header: "allpha",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "2f14910d-ff78-4a0f-8750-b9d1b2c0cb7b",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you're playing with the toy from your kids meal and your crush sits down next to you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "30e88709-6318-4e22-86ab-cc6727a7a4cf",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "demonstrate how you masterbate",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "3316a392-23fb-4639-87d0-2d3d98f5ab40",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you run into her at a halloween party dressed as trump",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "357f4393-97ba-414a-8b1e-9249d6d869ee",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you find out your crush is super into poetry",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "35984c25-b641-40b0-b793-e4d5d5c60aeb",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "been with a milf",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "35bc4557-a94b-43dc-8276-86e5a0fe2632",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who would drink a glass of piss for $100",
    header: "allpha",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "36faa4af-6015-4846-ac86-a64e8562f05a",
    game: "wildcard",
    pack: "boysnight",
    prompt: "who has a better 6 pack",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "373feee1-6b93-41e0-b72c-fcc018a05e4b",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "had swag",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "39defc0e-d684-430a-9888-c5bec74cb2f9",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: 'been cheated on with a "hes just a friend" guy',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "3bb7320e-2b40-4ca9-861d-4e70c94f1b01",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "name their son after an athlete",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "3c6d0165-91b1-41ea-92ca-6aca714fbba9",
    game: "wildcard",
    pack: "boysnight",
    prompt: "explain to the boys where the clit is",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "they decide,",
    sipFlag: 1,
  },
  {
    uuid: "3e0ed976-d3bb-4b52-9d7f-2efc564ba04d",
    game: "categories",
    pack: "boysnight",
    prompt: "pokemon",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "3e560179-5ae1-4dd3-abe8-31d5949cd73c",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "has the hottest mom",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "409bed83-98b5-4a44-83ea-d2bdc0040a38",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if you've busted in under 2 minutes",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "4371f039-f627-46f5-a090-b897bccd22ef",
    game: "wildcard",
    pack: "boysnight",
    prompt: "everyone who wacks it with their left hand",
    header: "tell us more",
    cardType: "GROUP",
    drinkHeader: "the guilty,",
    sipFlag: 1,
  },
  {
    uuid: "43dce5c1-1efe-4b17-b8bb-75fada8698e0",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you're ordering 3 fruity cocktails for your friends and the bartender's hot",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "451310a5-5e38-4309-9377-e4a411c42ae4",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "threaded my mustache",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "45e39777-f469-4ad1-aae9-5e3ce6c3cd61",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if you still know where you keep your beyblades",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "fess up, and",
    sipFlag: 1,
  },
  {
    uuid: "479a18cf-0d9e-48cf-85e4-423acf88ff3e",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "win fantasy football ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "47d9a258-e7bd-4167-9d6e-88596e2e11d9",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "tell the group your body count",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "4a534c16-1a0b-45de-a889-4d9ed5c3b29e",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "to end up passed out in a dirtch ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "4aa81bb7-9dbc-4311-96d1-357f944f7ac8",
    game: "wildcard",
    pack: "boysnight",
    prompt: "call out any of your eskimo bros",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "you each",
    sipFlag: 1,
  },
  {
    uuid: "4af776d1-705a-47b0-be99-774ab02c92ff",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "moon the group",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "4bedc597-03e8-4b83-b13f-2ebeb5ea2f21",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "tell you about how they are on the up and up",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "4f67f50f-74b5-4c85-b0b6-073ac14628fc",
    game: "wildcard",
    pack: "boysnight",
    prompt: "everyone who wacks it with their right hand ",
    header: "tell us more",
    cardType: "GROUP",
    drinkHeader: "the guilty,",
    sipFlag: 1,
  },
  {
    uuid: "51d15c98-0067-49e2-a2de-909e1c8da63d",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: 'let the group give you an "indian burn" ',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "539a4636-1f21-43b6-bbaf-a8e07880bb75",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get overly competitive at anything",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "55edb6ce-e848-4345-a8d9-371813e51cc7",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "wings or pizza",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "578e4a84-7bb9-4347-aae1-6327838fae1a",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if you have tasted your own cum",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "5a1fff71-2b8d-4e71-8eb3-b6021584d603",
    game: "wildcard",
    pack: "boysnight",
    prompt: "place an icecube under your arm pit for as long as you can",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "5abf69e6-6fc5-47ac-8573-085663ff7919",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "suggest going to the casino",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "5e478b04-5b3c-43de-9011-616b1c63435f",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "tell you about their idea for an app",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "5e55125a-b0ef-40e5-84f4-8e45d318ec08",
    game: "categories",
    pack: "boysnight",
    prompt: "types of sports cars",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "5e5dfc4b-180d-4060-9da5-da3b8036144e",
    game: "categories",
    pack: "boysnight",
    prompt: "mario kart characters",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "61797fc4-2bfe-4f24-8339-d2393be9a0bf",
    game: "wildcard",
    pack: "boysnight",
    prompt:
      "how much change do you get if your total is 17.71 and you gave them a 20",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "63503b6a-6c97-4aec-994f-134906fd7b25",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get turned on from anime",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6482454f-0db4-4a33-8c08-535093365b99",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "to win a hot dog eating contest",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "64d5d3b6-5ed5-4c74-9f27-99c02c22e1d4",
    game: "wildcard",
    pack: "boysnight",
    prompt: "name 5 pro football teams in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "6568237d-6628-46b6-b2e4-3e0191189903",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "she walks in on you 14 episodes deep into a dragonball z binge",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "661fa33d-2094-43ce-90aa-2793deb3f3d7",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if anyone still possesses unopened pokemon cards",
    header: '"They\'re Collectibles"',
    cardType: "GROUP",
    drinkHeader: "fanboys",
    sipFlag: 1,
  },
  {
    uuid: "6630eef8-cf1e-4187-962a-397ebfc9b268",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "seen a ghost",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "66421ae2-f985-4e69-af7e-23906a9d10e8",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "has gotten with the hottest girl",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6b5c5918-e061-4b84-9523-88c452fb6f8d",
    game: "wildcard",
    pack: "boysnight",
    prompt: "whoever has a longer wing span",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the ape",
    sipFlag: 1,
  },
  {
    uuid: "6c54d3d9-11dc-4f5c-a7a4-3981d8a526bf",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "bad boy or nice guy",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "6ea75ca2-4ee8-4446-94d7-9ca59db0624c",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who has taken the grendate for your boy",
    header: "allpha",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "701c98d0-2880-48bd-88e2-92c1e4f1c68e",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "she joins your twitch stream of 7 viewers",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "714d40f2-58e5-45e7-b304-0a238786bffa",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "try wrestling moves on their partner",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "715fcff5-3582-440b-a6c8-26e849b8c1a6",
    game: "categories",
    pack: "boysnight",
    prompt: "things you find in your pocket",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "730079d4-342d-4c67-aff6-88f1ed2502ec",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "lose everything playing backgammon online",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "736290d7-0f0a-4ef3-8fd6-03dcd2541397",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "try and rap freestle at any chance they get ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "739eeb2e-2979-43c9-8bb0-c512ad52140a",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "try and convince you to invest in something",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "73bd822b-8e31-412c-a099-f61a3c15a000",
    game: "wildcard",
    pack: "boysnight",
    prompt: "whoever can name the most jutsu's from Naruto",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -2,
  },
  {
    uuid: "74f206af-2c33-4534-8c3b-3f930cd165f5",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "been a cockblock",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "755cc381-4cc0-4ecc-a3b5-d9ff430ab35c",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who's been to a strip clup in the last year",
    header: null,
    cardType: "GROUP",
    drinkHeader: "pay up, and",
    sipFlag: 1,
  },
  {
    uuid: "763d9f17-b589-4f5a-9ad4-c93869ef2340",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "post a snap of yall and say for the boys",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "7ab32f5b-d6ca-4dd2-94e1-d0f246110a12",
    game: "categories",
    pack: "boysnight",
    prompt: "video game consoles",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "7c5bc1bc-9306-47f1-938e-427991bf8428",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "beer bonged",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "7e6fc584-b200-483b-92b0-c5e7fb0f5f57",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get arrested for public urination",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "82002d37-7592-4234-94fd-4c5cdb71c482",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "to win at super smash",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "82039560-9009-418e-bffc-295e21b4773f",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "end up on an esports team",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "842f0c92-136c-4d4e-a38a-cb826718395f",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "smash their controller in rage",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "84f388fd-3240-4578-b1e4-8d24007bac41",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "let the person next to you send a peach emoji to anyone they want",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "868dac7d-dc63-48db-8eac-fe5866918a43",
    game: "wildcard",
    pack: "boysnight",
    prompt: "who is the hairest overall",
    header: "chubaka",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: -1,
  },
  {
    uuid: "8751b708-8f78-4ae8-827a-10e2bf7a92c4",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who has had a condom break during sex",
    header: "oh shoot",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "88d3aa1e-e514-498d-b0c4-e687de90e2ab",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have a boner right now",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "89661abf-aa12-45a5-9268-a4a12a0b7b48",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "boobs or butt",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "8a2049c6-15af-4885-baa1-590af81d9c39",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "be the biggest nerd",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8e421fcf-4005-4223-a6b0-6466b38f6fec",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "taken an everclear shot",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "925c6182-cf6e-463b-b8af-72b85fe36ad3",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "a bachelorette boat party discovers you stranded at sea in a pool flamingo",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "92c0a33b-f403-4a28-9bc4-2e908fae0d39",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "act poor",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "9474e194-4867-4448-b6b3-f28aa5df4e8c",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "has the hottest sister",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "947bbaba-5e76-4076-a510-0eff53c84b4f",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have a sports bet open right now",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "950c150f-7b92-4f2e-ae7b-d8879ce90dc0",
    game: "categories",
    pack: "boysnight",
    prompt: "teams in the champions league",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "992a23f6-8c00-47b0-9b07-0a054d208de9",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "entered a gaming tournament",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "99375617-e89f-4222-8462-dfdc6596bda4",
    game: "wildcard",
    pack: "boysnight",
    prompt: "name 3 fire type pokemon in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "you've earned these",
    sipFlag: 1,
  },
  {
    uuid: "99541979-ef25-499c-838a-218444eb49d7",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if you've ever watched didgimon as an adult",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "99ee700c-9bd9-498e-b998-8baf2226c297",
    game: "categories",
    pack: "boysnight",
    prompt: "hockey teams",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "9abf4c0b-3dcd-4591-aaaf-937559544eaf",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "end up an overactive kids sports coach",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "9ca8995e-6704-4617-ab8c-b4d02ddc2e22",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you're getting extra beans on your chipotle burrito and notice the worker's cute",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "a0ccb42f-96b8-4f24-ad19-3080947e4a97",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "big or shredded",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "a1703dbf-c96a-4c77-9d1d-51b5b089b944",
    game: "wildcard",
    pack: "boysnight",
    prompt: 'anyone who has used the word "females" tonight',
    header: "FEMALES",
    cardType: "GROUP",
    drinkHeader: "the guilty,",
    sipFlag: 1,
  },
  {
    uuid: "a24a71d9-a689-411a-ada1-428e70a263af",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "boxers or briefs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "a336e869-240e-436e-8374-89208bbabcb4",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you sit down to bench and a girl accidentally sits on your face",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "a392b9dd-7727-4f83-8472-56f733e3e10f",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: 'not listen to your story and then say "damn, thats wild"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a3ac671b-54aa-45c3-9cc1-1dd597b15eec",
    game: "wildcard",
    pack: "boysnight",
    prompt: "if your dick is smaller than drake's",
    header: "You Got It Like That?",
    cardType: "GROUP",
    drinkHeader: "all normal humans",
    sipFlag: 1,
  },
  {
    uuid: "a4643a7e-3910-4e33-8efb-0ca4c099020a",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who would eat a bull testicle for $500",
    header: "allpha",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "a5b97b77-5e01-47ba-8199-ef67f6ef5d3d",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get on the sex offender list because of public urination",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a7c512c6-22ad-4102-b5ae-d8a2a843c730",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get friend zoned",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a99dadfa-b1bf-442b-a4f3-070e21b44910",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "take a shot with someone of your choice",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "ac26e687-9765-4f6c-9174-79c1b63454a4",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "pink eye or double ear infection",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "ada3231d-207b-4b6c-bea2-42d71be324ae",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you're buying extra strength deodorant from cvs and the cashier's a 10",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "aed63f5f-8369-4dcd-8088-39898dfab369",
    game: "categories",
    pack: "boysnight",
    prompt: "synonyms for vagina",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "b280cab9-8efe-4540-af09-4bdfcbb40182",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "meghan fox or scarlet johanson",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "b2e27997-1dfe-4d83-987d-7718c48999f2",
    game: "wildcard",
    pack: "boysnight",
    prompt: "who can hold your breath longer",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "b6aa7da8-af34-4646-bf9f-a5c1700754d9",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "get caught staring at a butt",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "b8627494-85b2-49d1-b81e-ace0c9d15ef6",
    game: "categories",
    pack: "boysnight",
    prompt: "sports involving a ball",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "b869cad5-23b3-4548-b857-c7f13f6b46f4",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: " to have a foot fetish",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "b909279b-a552-443a-8c69-cca640287709",
    game: "wildcard",
    pack: "boysnight",
    prompt: "anyone who's ever paid for a lap dance",
    header: null,
    cardType: "GROUP",
    drinkHeader: "thirsty spenders",
    sipFlag: 1,
  },
  {
    uuid: "b9834f10-b1ab-4fe6-9c3c-61b26b5166fa",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "be involved in baby mama drama ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "bb0634e6-5bfe-42f7-ab16-ba6d3477d382",
    game: "categories",
    pack: "boysnight",
    prompt: "olympic sports",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "bbd74619-cf6c-4937-bf74-1b6615331862",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "gone 100 swipes without a match",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "bcc7c292-9fd0-41ae-8066-7bc2239f3739",
    game: "categories",
    pack: "boysnight",
    prompt: "super smash characters",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "bd543c40-2a83-41a8-a012-3e430960320c",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "be a rat or a little bitch",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "bd7f5b94-8845-45b5-976e-aec55a6e1b6e",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "listened to the joe rogan podcast",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "be847556-efe2-44a0-9c1e-c5e159f2305b",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "plus sized or midget",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "c21ecaea-cb00-4de2-9446-feea4a2e7565",
    game: "wildcard",
    pack: "boysnight",
    prompt: "whoever can name the most pokemon",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -3,
  },
  {
    uuid: "c6c62ba6-e5ea-4507-850f-c821678d3256",
    game: "wildcard",
    pack: "boysnight",
    prompt: "race to name 4 kinda of soda",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "c6f8bac6-b2ba-4da1-b3b7-8ee00ef8d47e",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: " to be a 40 yr old virign",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "c928a0a6-a80e-4d90-8c70-5e883b2d1d50",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "point out a butt",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "ca606e17-8786-4fca-8853-10a31c0dc20b",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "done a jaeger bomb",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "cfaaf02a-de4c-446f-a741-7d668c372635",
    game: "wildcard",
    pack: "boysnight",
    prompt: "best mustache",
    header: "UH HUHH",
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d030c3ad-2b9d-4083-97b8-cf2561b1cf07",
    game: "wildcard",
    pack: "boysnight",
    prompt: "Everyone wearing  jewelry",
    header: "Pretty boy",
    cardType: "GROUP",
    drinkHeader: "if you are,",
    sipFlag: 1,
  },
  {
    uuid: "d303f19d-7e58-454e-a01f-88df5e19de42",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "brag about their shotgun time",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d384dafb-b4e3-468f-b897-9a2878809b40",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: 'say "thats what she said" after literally anything',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d46c5227-2795-4258-bd70-2321eab9bfc5",
    game: "wildcard",
    pack: "boysnight",
    prompt: "your bill is $140 and you want to leave a 15% tip",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "d5cf8cf8-8b51-4aab-9f8a-3e66cfbaabd8",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have a baby mama",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d6b5955a-0107-40eb-80b5-acc37c5d812e",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you go to the docs for your erectile disfunction and she's a dime",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "d6d74eb6-f7d2-4b9b-a375-929ad4386226",
    game: "wildcard",
    pack: "boysnight",
    prompt: "words that rhyme with beer",
    header: "rhyme",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "d71a6705-4d1c-4aeb-b91d-a15ad0154a7d",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "smash just about anything",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d7702c27-4d36-4d1f-a0bb-b761527b7cb8",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "you're checking out with extra small condoms and your crush walks by",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "d809838d-ba6c-448a-9be1-5b95e23f5afc",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "your pubes are sticking out of your speedo at the beach and she notices",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "df4bb3f3-0e6f-43b5-a15b-50830a58304e",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "she just found out you failed anatomy for the 2nd time",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "e1a4a14e-d809-4caf-ae04-a020678189f2",
    game: "wildcard",
    pack: "boysnight",
    prompt: "give us your best dad joke",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "e31e3e6e-a7ff-4367-945c-deeb30b3b2ef",
    game: "wildcard",
    pack: "boysnight",
    prompt: "have you seen anyone in the group's dong?",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "for each one,",
    sipFlag: 1,
  },
  {
    uuid: "e39b439e-ebd7-49b5-abd4-32fc39f6e8b9",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "the hot eskimo girl next door's igloo has collapsed and she needs somewhere to stay ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "e4127d51-e8b8-4827-a363-75600c816320",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "shotguned a beer",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e649d7fe-7ad9-4d05-9de6-1995d913c4d0",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "you go to her birthday party but forgot to bring a gift",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "e68b47a5-0332-414d-8cdd-aac577fc96d4",
    game: "wildcard",
    pack: "boysnight",
    prompt: "whoever has the nicest butt",
    header: "bubble butt",
    cardType: "GROUP",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "e6d8f237-88dd-4969-9980-c0578e6b4b37",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: 'dated somoene just for their "personality" ',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e75d12a7-8622-4bcc-a69c-a6d955db41c7",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt:
      "your crush catches you dumpster diving for your crypto wallet seed phrase",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "e8c469fa-ce3b-4e27-8f3d-49b4660db912",
    game: "rizztraining_order",
    pack: "boysnight",
    prompt: "there's a girl in front of you at target buying pokemon cards",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "rizz her up, or",
    sipFlag: 1,
  },
  {
    uuid: "ea9f0c7d-6e49-432f-ae4d-778800416b5d",
    game: "wildcard",
    pack: "boysnight",
    prompt: "everyone size 8 shoe or below",
    header: "lil feet",
    cardType: "GROUP",
    drinkHeader: "little ones,",
    sipFlag: 1,
  },
  {
    uuid: "eb46eb44-c5c6-4c0a-a631-4ebea006432e",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "to point out a hot girl",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "ef1339a9-3889-4a4e-90f2-2faa16070b1c",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "have the higest testoerone",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "f3d5bbac-83b5-4b9a-8e96-67749952a98e",
    game: "never_have_i_ever",
    pack: "boysnight",
    prompt: "picked a fight for no reason",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f5ccc2eb-8972-48b6-a60b-7dec5c90fe0e",
    game: "wildcard",
    pack: "boysnight",
    prompt: "first to guess which ocean is next to India",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: 1,
  },
  {
    uuid: "f715058b-f9af-4b95-b5aa-c8e6dbf8fcf1",
    game: "categories",
    pack: "boysnight",
    prompt: "football teams",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "fb21171c-f373-4b76-a658-a0c8cfdacc93",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "be a step dad",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "fb5bae01-8246-41c8-8ed6-53ea3a93701e",
    game: "most_likely_to",
    pack: "boysnight",
    prompt: "change how they act when a girl is around",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "fd5daabb-5f22-4565-9b6a-e29d70810249",
    game: "this_or_that",
    pack: "boysnight",
    prompt: "rich & everyone hates you or poor & everyone loves you",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "98cc92f8-8d9b-4a27-aa4b-34f3b3e31adb",
    game: "wildcard",
    pack: "boysnight",
    prompt:
      "the entire groups makes a human pyramid - succeed and you are safe",
    header: null,
    cardType: "GROUP",
    drinkHeader: "fail and all,",
    sipFlag: 1,
  },
  {
    uuid: "a0738a73-bbcc-4917-b07b-ad05e99e5928",
    game: "wildcard",
    pack: "boysnight",
    prompt: "who can hold a plank longer",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner,",
    sipFlag: -1,
  },
  {
    uuid: "ae572f86-77d0-438e-9797-4823bf45bdcd",
    game: "wildcard",
    pack: "boysnight",
    prompt: "body weight squat off",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner,",
    sipFlag: -1,
  },
  {
    uuid: "4c2ea1b9-9c7b-4d93-919f-a7426d4131f5",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "show us with your hands the size boobs you like",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "b2061c4e-60c0-4b46-9082-4de05cfd324b",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: "show us with your hands the size booty you like",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "6a7eabea-c9b7-46ea-a656-7771a51937fe",
    game: "do_or_drink",
    pack: "boysnight",
    prompt: 'send an email and as the footer say "Sent with my 1eyedCobra"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "cb2ad105-26b0-4187-9aae-54e57f476644",
    game: "wildcard",
    pack: "boysnight",
    prompt: "try and bench press the lightest person here",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "succeed and,",
    sipFlag: -1,
  },
  {
    uuid: "1de941e1-c785-41f4-a5c2-9057203071b5",
    game: "wildcard",
    pack: "boysnight",
    prompt: "do a body squat with the person on your right on your back",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "succeed and,",
    sipFlag: -1,
  },
];
