export default [
  {
    uuid: "01d0bde0-eb91-4f74-a8c0-1523e32cf096",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who dosen't reciprocate oral sex",
    header: "you konw who you are",
    cardType: "GROUP",
    drinkHeader: "the lazy,",
    sipFlag: 1,
  },
  {
    uuid: "02a0ac96-67e8-440f-b967-fb83a47eea4e",
    game: "this_or_that",
    pack: "chaos",
    prompt: "fuck your dad or mom",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "03272f20-715a-4bb2-b33d-67a4af1a28b9",
    game: "wildcard",
    pack: "chaos",
    prompt: "whoever is showing the least amount of skin",
    header: "CLOTHED",
    cardType: "GROUP",
    drinkHeader: "least skinned,",
    sipFlag: 1,
  },
  {
    uuid: "03aac097-7318-466a-be70-32c6bbb06adc",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "given or recieved a golden shower",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "03fb1f10-acbe-4444-bd8a-6436fffa6e2c",
    game: "wildcard",
    pack: "chaos",
    prompt: 'play "nervous" ',
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "0403ce1b-b286-479a-a89b-a65ea54afadf",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "give a hickey to the person on your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "0740e7a0-9383-4c8a-b717-26f480cbf01a",
    game: "categories",
    pack: "chaos",
    prompt: "drinking games",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "0882d794-71cb-4d45-8b7c-d6f796466a2d",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "name the sexiest feature of everyone in the group",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "0a15956d-6c95-4255-b334-78afca49bf71",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "give an unpopular opinion",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "0a940c0a-666a-432e-947b-eaf11365576a",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "on the count of 3, everyone scream who is the most annoying person here",
    header: "did you do it?",
    cardType: "GROUP",
    drinkHeader: "participate or,",
    sipFlag: 1,
  },
  {
    uuid: "0c2acd58-6eee-4b2c-92f5-b9cd28062aeb",
    game: "wildcard",
    pack: "chaos",
    prompt: "roast eachother",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "0d361d03-2318-4465-9d91-0604ae7c2964",
    game: "wildcard",
    pack: "chaos",
    prompt: "twerk off",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner,",
    sipFlag: -1,
  },
  {
    uuid: "0dd63cc2-235e-4b16-9433-36eca2e936fa",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us which two people would make the best couple",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "0de8d824-1106-4cec-8130-00ee1c9085b9",
    game: "wildcard",
    pack: "chaos",
    prompt: "if your parents are dissapointed in you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "0f7c2877-d2ee-4463-a5d0-afd25c0599be",
    game: "wildcard",
    pack: "chaos",
    prompt: "from now on everyone pees in the sink",
    header: "thats right",
    cardType: "GROUP",
    drinkHeader: "refuse and,",
    sipFlag: 3,
  },
  {
    uuid: "0ffba2f9-cb72-4262-9333-368a89806072",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'text your parents just "pregnant"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "11268006-9807-4493-a2c1-fd4c9b682bd9",
    game: "wildcard",
    pack: "chaos",
    prompt: "lick the nipple of the person to your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -3,
  },
  {
    uuid: "124e7b6b-f28e-4d3f-8923-8f632bff7518",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone here who you have kissed",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "make them,",
    sipFlag: 1,
  },
  {
    uuid: "17d79274-6e61-4fe1-beb7-3a457d1e761b",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "text your last sexual partner telling them you have herpes",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "1a0bcf06-2d3e-444b-9993-3939095dd41d",
    game: "wildcard",
    pack: "chaos",
    prompt: "name 3 sex toys in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "1b44b19a-ad46-4a05-a8bc-f7e65773198c",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'text your ex "I miss you"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "1ba0322f-964d-497f-a813-d839ef3393ca",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone who has seen you puke",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the guilty,",
    sipFlag: 1,
  },
  {
    uuid: "1eca1d71-9af8-41cd-8a2b-adf546e8c1a5",
    game: "categories",
    pack: "chaos",
    prompt: "songs about partying",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "2111f641-408d-46e7-814c-e60d7f56d16d",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "gone to an after party just to hookup",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2148227b-d1bd-4d1a-837d-dc13c80d6455",
    game: "categories",
    pack: "chaos",
    prompt: "beer brands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "226ae871-1242-4373-948e-20e3d95532c3",
    game: "wildcard",
    pack: "chaos",
    prompt: "pick 2 players to share a 3 way kiss",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "do it and,",
    sipFlag: -3,
  },
  {
    uuid: "26d03426-e178-4a70-9300-63675d9a000e",
    game: "wildcard",
    pack: "chaos",
    prompt: "insult everyone in the room",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the best,",
    sipFlag: 1,
  },
  {
    uuid: "27e3bcd8-e7ef-42bd-b911-ffe485dd5bd6",
    game: "wildcard",
    pack: "chaos",
    prompt: "shotgun race",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner,",
    sipFlag: -1,
  },
  {
    uuid: "27ec3da1-6d17-4fba-ba3b-8a695067c598",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone whose seen midget porn ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "28806918-03ea-4ef9-bc57-89d94fc9375f",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "tried to finger my own asshole",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "28a4a16a-5848-4679-a792-2ca80659c2bb",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "slip a finger in the ass without warning",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "28f3a57f-1b9b-4305-bce7-edd3a2116168",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "masturbated while your partner was asleep next to you",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2bda78e5-238a-4bac-a5bc-4b35ec58bb5c",
    game: "wildcard",
    pack: "chaos",
    prompt: "if you have given oral in the last 24 hours",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "2f995bd3-bf29-45ef-ae46-35404729bf48",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who prefers being on top",
    header: "sexy",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "2fd983ad-25c0-4bc9-8c5b-67a93b724b02",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "give a lap dance to someone of your choosing",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "32f9c738-a9f3-4901-9c05-7950b2bec236",
    game: "wildcard",
    pack: "chaos",
    prompt: "stick your tongue in the ear of the player to your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and both,",
    sipFlag: 2,
  },
  {
    uuid: "34752424-d633-45bc-867d-3872b449aa5d",
    game: "wildcard",
    pack: "chaos",
    prompt: "would you stick a roll of quarters up your ass for $100",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you would,",
    sipFlag: 1,
  },
  {
    uuid: "35465c2b-66f4-4269-ab17-85cb15000a75",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "been to a swingers party",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "38e1635e-7baa-4acd-be12-f7f93d818076",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who would lick a homeless persons asscrack for 20k",
    header: "ur gross",
    cardType: "GROUP",
    drinkHeader: "nasties unitte and,",
    sipFlag: 1,
  },
  {
    uuid: "39c33c45-bad4-458b-a4cc-2d7a235cc0ca",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone who will try VR sex",
    header: "sexy",
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1,
  },
  {
    uuid: "39c812cc-cb01-44cf-830b-74b7579bed5b",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "do a fuck,marry,kill out of the people here",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "3e4902fd-fbc6-47d8-9f15-fe5480ea65f3",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "order a pizza and make sure to ask for the driver to have an extra large sausage",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "4186347e-eb41-4c84-9e10-cb41d67aff8c",
    game: "wildcard",
    pack: "chaos",
    prompt: "the player to your right smacks your ass",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and both,",
    sipFlag: 2,
  },
  {
    uuid: "455f7f46-dc73-4d80-9d95-801a879efb96",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "stolen a glass from a bar",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "45dba803-3cc0-4048-8107-7639c21d60c7",
    game: "wildcard",
    pack: "chaos",
    prompt: "call your dad and say you are in jail and need bail money",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -1,
  },
  {
    uuid: "48469412-031f-4246-b456-e5de0653a2f8",
    game: "wildcard",
    pack: "chaos",
    prompt: "take a shot off the person to your rights belly button",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -3,
  },
  {
    uuid: "48d3dad6-a12c-441a-8326-249c600c8946",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "write your initials with your tongue on the person next to your neck",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "48f5fb4e-b6c9-4780-a34e-fe3de4d44e80",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'call your mom and ask if they have any "hard black caulk"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "490f86e8-1d2c-4240-aced-490ec2b6dd57",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "Everyone put your drivers license in the middle, vote on the worst pic",
    header: "cheeze",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "4ceb7f21-1a67-4359-8ba7-0160c783815c",
    game: "wildcard",
    pack: "chaos",
    prompt: "name 3 strands of weed",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you lose,",
    sipFlag: 1,
  },
  {
    uuid: "55ee7970-0e61-4ba3-bc86-06b0233c9fec",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "make it look like someone pissed their pants and post a pic on snapchat",
    header: "Not again",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "5836d8b4-ae4d-4a9a-bb89-53ef4607c2b5",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "show everyone your bank account",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "5a3bbb09-599c-48b0-937e-0df78a4027ea",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "unknowing end up in bed with a transvestite",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "5a46c934-16f6-4004-862e-14c0b0318762",
    game: "wildcard",
    pack: "chaos",
    prompt: "throw your wallet up against the ceiling and try and catch it",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -1,
  },
  {
    uuid: "5efeae92-3858-42cb-9915-48904b4ff653",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "kiss the person you know the least",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "5f196508-c3bd-486b-a49a-3fe3fb123431",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "lick the floor",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "5fe23cd0-7b76-4f0e-aeb9-8d8fa68c8719",
    game: "wildcard",
    pack: "chaos",
    prompt: "sexually suck on the finger of the person to your right",
    header: "?",
    cardType: "GROUP",
    drinkHeader: "do it and,",
    sipFlag: -1,
  },
  {
    uuid: "63150166-76ad-4f6d-9958-da51c5332498",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "lose the pants",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "64768489-cf08-46e2-a7cb-7807e85ea649",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "flash the group",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "684c402f-994e-4b46-a737-218b4486f33c",
    game: "wildcard",
    pack: "chaos",
    prompt: "call a grandparent and say you are high right now",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "complete it and,",
    sipFlag: -1,
  },
  {
    uuid: "6a776a35-dc28-49f2-8a4d-35fec6683971",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "stick your finger into the top of the buttcrack of the player to your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "6bc911fb-dcc1-4022-8714-e5fa3a939986",
    game: "wildcard",
    pack: "chaos",
    prompt: "unzip the person to your rights pants with your mouth ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and,",
    sipFlag: 3,
  },
  {
    uuid: "6c380949-cf00-47bf-8ab0-ed6cb8d8bbf5",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'text your mom saying "I got a eight for $40"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "6d23b929-a1ea-4695-a7c9-4c71100f682d",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "bent over and looked at my asshole in the mirror",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "6d3cbfb7-4e33-4764-94cc-5ba8ab5aa11f",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "rub the knee of the player next to you for 20 seconds as you stare into their eyes",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "6fd67168-5a80-4515-8ef6-fa36432223ec",
    game: "most_likely_to",
    pack: "chaos",
    prompt: 'search "BDSM" on a porn site',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "71fbf9d8-6b5d-4c48-a513-b443000d6814",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "put the person on your left on your shoulders",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "72babd06-dcb7-40d4-9a99-aefc5f4e1490",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone take turns giving us your best dirty talk",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "7310b9a1-d5d4-41bf-821b-8adf89a7cf81",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "let the group spoon feed you something while your eyes are closed",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "76778066-5a5d-41d0-947f-e3de798918d9",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "fill your mouth with beer and puff out your cheeks, then let someone push your cheeks together",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "7c5b50ec-3a04-44f0-8fc9-636b3e8cccd3",
    game: "wildcard",
    pack: "chaos",
    prompt: "motorboat the person to your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -3,
  },
  {
    uuid: "805bed16-a874-4688-af10-146fb3099483",
    game: "wildcard",
    pack: "chaos",
    prompt: "guess the color of the person to your right's underwear",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "get it right,",
    sipFlag: -1,
  },
  {
    uuid: "810e3a28-5961-49e4-bea0-ebbf0d74b8c0",
    game: "wildcard",
    pack: "chaos",
    prompt: "lead us in performing the human centepede",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "any participants,",
    sipFlag: -3,
  },
  {
    uuid: "81f33660-6892-4e16-b075-2efb657cfd0b",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "confess your biggest insecurity",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "8616b6db-8484-426e-9cdc-51e7202a4374",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who owns anal beads",
    header: "sexy",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "893441bd-8a1a-4705-93f0-6b2a6a957829",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "give the player to your left a bare ass naked butt massage for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "8989119c-c3f9-4861-860a-6efb68e98bab",
    game: "wildcard",
    pack: "chaos",
    prompt: " for every month you've been single",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "8b3bfa04-40c1-4442-8644-2241ca21b760",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "Gotten a DUI",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "8c7cc051-6868-4e0a-b435-bcc44a676163",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "end up taking the aux and putting shit music on",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8f572611-76a2-4b1a-908e-d4cb83e4895b",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "rub the earlobe of the player next to you for 20 seconds as you stare into their eyes",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "916f3894-767d-4351-90b1-1f5b6cadd766",
    game: "wildcard",
    pack: "chaos",
    prompt: 'text your sibling "Ugh, I wish we lived in West Virginia"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "complete it and,",
    sipFlag: -2,
  },
  {
    uuid: "92441b7a-24f1-4e7e-9c3d-0f4db75e7d91",
    game: "this_or_that",
    pack: "chaos",
    prompt: "gay son or thot daughter",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "9306e92f-cf5d-4c3d-852f-276311d3b339",
    game: "wildcard",
    pack: "chaos",
    prompt: "name 3 porn stars in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "9428dd99-497e-4467-8ddb-d6ec8e307fb5",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who would have sex with their cousin for 50k",
    header: "yes, you ",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "96bdba97-eff9-4ea7-ab61-8e191aedf8d9",
    game: "wildcard",
    pack: "chaos",
    prompt: "send your mom a dick pic",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and,",
    sipFlag: 3,
  },
  {
    uuid: "98906d48-e677-4347-9bbb-f8dc82bd31a9",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'text your mom or dad, "I just got back from the clinic"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "9b272717-fef3-4107-b18a-9512fc8047d8",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone tell us who you voted for ",
    header: "Not again",
    cardType: "GROUP",
    drinkHeader: "if you refuse,",
    sipFlag: 1,
  },
  {
    uuid: "a833c2bf-ab75-4f60-bf8b-a9335ac15b3d",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "bite the person to your right",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "a8be15dd-94b3-4e26-94bc-04e86b8c31c2",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "on the count of 3, everyone scream who is the most annoying person here",
    header: "did you do it?",
    cardType: "GROUP",
    drinkHeader: "participate or,",
    sipFlag: 1,
  },
  {
    uuid: "ac79821b-b9db-477c-9e54-68db94fcfcc4",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "benefit from anger managment",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "b0b1f999-6ead-4fc2-82e6-5fd9d1e30a9a",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "swap pants with someone of your choice",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "b4082a1b-9d91-4510-ad77-9d7299703f85",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "die alone",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "b449aa9f-c57f-45d6-b64b-3d2b231c2149",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us whose name would be the best pornstar",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "b6660676-59c1-4a55-9554-9c2bbdbd8cec",
    game: "wildcard",
    pack: "chaos",
    prompt: "recieve a double titty twister from players on either side of you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "succeed,",
    sipFlag: -2,
  },
  {
    uuid: "ba3974d6-8d9c-452f-b189-8385a0f49b5e",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "stayed with a cheater because the sex was dope",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "bca5e37c-d00d-48de-baa8-5fca151b7bf1",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "give the person to your right a backmassage while whispering dirty things in their ear for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -2,
  },
  {
    uuid: "bface7e1-07cc-4b15-99e0-b6c8d29004ec",
    game: "wildcard",
    pack: "chaos",
    prompt: "first to pull out a condom",
    header: "con - DEM",
    cardType: "GROUP",
    drinkHeader: "winner,",
    sipFlag: -1,
  },
  {
    uuid: "c05efbb4-582a-443d-8709-a5cdd3127307",
    game: "categories",
    pack: "chaos",
    prompt: "things you would do for 10k",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "c12789a5-5812-4687-aa74-c7131987c69d",
    game: "do_or_drink",
    pack: "chaos",
    prompt: 'let the group snapchat someone "nudes"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "c257430d-cd63-4a20-8f70-daceb9d1115a",
    game: "wildcard",
    pack: "chaos",
    prompt: "lay a big wet one on the player to your right's lips",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and both,",
    sipFlag: 2,
  },
  {
    uuid: "c537a21f-db1b-475c-b80d-c7557f22b206",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "let the group put tape on your body and rip it off",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "c62e2e97-cd00-4c72-ae50-88023f64158d",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "let the group tickle you for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "c75d5bf8-3aa0-4c4f-ac07-adc1f970f0b7",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "let the person next to you draw a mustache on you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "ca1d4cd6-59bb-4991-a365-e65c666f488a",
    game: "wildcard",
    pack: "chaos",
    prompt: "call Walmart and try and make a birthday reservation ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "complete it and,",
    sipFlag: -1,
  },
  {
    uuid: "cc1226c9-bad5-4b59-aec0-c005b3dff8c2",
    game: "wildcard",
    pack: "chaos",
    prompt: "balance a cup of water on your head for 5 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "ce141d23-2011-4623-b128-46a08773e984",
    game: "most_likely_to",
    pack: "chaos",
    prompt: " puke tonight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "cfd3ac71-3b7f-4183-b544-d9df8cce5899",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "take turns giving each other wedgies, the group votes on the best form",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "most voted,",
    sipFlag: -1,
  },
  {
    uuid: "d17d753f-79a5-4b74-9f9c-6db6f8d62478",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "only in underwear, go ask the neighbor to borrow duct tape",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "d18b5a3f-ec42-471f-b8de-863b23c7f230",
    game: "wildcard",
    pack: "chaos",
    prompt: 'words that rhyme with "Dick"',
    header: "rhyme",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "d5ffa149-0322-417e-ab1c-af7b904b9be7",
    game: "wildcard",
    pack: "chaos",
    prompt: "anyone who prefers being on bottom",
    header: "sexy",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "d6c94a83-111c-44a2-839d-a4dcac8c6a70",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "give the person next to you a TSA pat down",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "d6de57b4-d667-41ef-8c21-bd2a0ca9a2f4",
    game: "this_or_that",
    pack: "chaos",
    prompt: "piss in the sink or shit in the shower",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "d90794e2-25e0-4a95-866f-e6fdfa4c7c16",
    game: "wildcard",
    pack: "chaos",
    prompt: 'call a store and ask if they sell "plan C, plan B didnt work out"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "do it and,",
    sipFlag: -3,
  },
  {
    uuid: "dcaecafd-d1ed-4843-b8f0-8a9749c2d7d3",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "smell the person to your lefts butt and get in there deep",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "dd508d13-a0db-461a-b90a-fab54cb243a6",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "reenact chasing your lover through the airport to confess your love",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "do it and",
    sipFlag: -2,
  },
  {
    uuid: "dd751bf8-28fa-4483-99d2-a0e7d6c7c47a",
    game: "wildcard",
    pack: "chaos",
    prompt: "Everyone with blonde hair",
    header: "dumb blondes",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "dd7fb3ea-9952-4d45-b304-db135ebf5283",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "From now on if anyone takes a shit you must take a pic and share it with the group",
    header: "Biiiig shitter",
    cardType: "GROUP",
    drinkHeader: "if you dont,",
    sipFlag: 1,
  },
  {
    uuid: "ddbd30ef-e4f7-4389-8f42-f24a52375201",
    game: "this_or_that",
    pack: "chaos",
    prompt: "weed or alcohol",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "e2ad6230-b67a-48e6-9ba0-15e18e0d6a06",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "had sex in this location",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e441420e-8792-4b0f-ae4a-8083cea0fa26",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "done a line of coke off someones body",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e4ac9b82-4e24-4d9d-90ea-958c6700e102",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "line everyone up based upon how much you think their net worth is",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "e5c5d845-4641-4e5d-9d94-c19ce7cdc45f",
    game: "wildcard",
    pack: "chaos",
    prompt: "put an icecube in your mouth and transfer it around the group",
    header: "GLHF",
    cardType: "GROUP",
    drinkHeader: "whoever drops it,",
    sipFlag: 2,
  },
  {
    uuid: "e71c75d4-db43-41a1-a73e-da616314f05f",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell everyone your salary",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "e772477b-dd91-40b8-b5c8-5db5b951050c",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone drinks",
    header: "ha",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 0,
  },
  {
    uuid: "ea42f0c9-b9c0-48e1-9226-57fa1ce6e75f",
    game: "most_likely_to",
    pack: "chaos",
    prompt: "have bought someone a drink tonight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "ec44cdf7-dd70-41d0-bb64-ee54626f1897",
    game: "this_or_that",
    pack: "chaos",
    prompt: "beer or liquor",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "eca09e25-0598-4eb6-9dde-6be86c50311e",
    game: "wildcard",
    pack: "chaos",
    prompt:
      "if you finish your drink, you can make someone go get you a new one",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 0,
  },
  {
    uuid: "ed6264b7-b330-49e1-8a85-edd966e6f821",
    game: "wildcard",
    pack: "chaos",
    prompt: 'publicly venmo the player next to you "butthole shaving"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: -3,
  },
  {
    uuid: "eeb9fdd7-6321-4897-b705-bb1febfa6735",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "call McDonalds and ask to set a reserveration",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "ef551854-4a38-424a-8160-c2587986ab8e",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell everyone your prefered porn category",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "f1b4e8af-9fb8-4e8d-87c5-2dfc264be979",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "maintain eye contact and unzip someones pants",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "f35cd57c-2312-49d8-b109-d64662e790ad",
    game: "wildcard",
    pack: "chaos",
    prompt: "if your pubes are shaved",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "f360a2b2-ec51-47c5-8bf0-ec5e37c961d4",
    game: "wildcard",
    pack: "chaos",
    prompt: "suck on the big toe of the player to your right",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "do it and,",
    sipFlag: -4,
  },
  {
    uuid: "f9fae8f2-512a-4457-a44c-b0d853223e84",
    game: "wildcard",
    pack: "chaos",
    prompt: "everyone do the worm",
    header: "do it",
    cardType: "GROUP",
    drinkHeader: "the best,",
    sipFlag: -1,
  },
  {
    uuid: "fa2ca16b-9f8b-4d5d-b740-8b0e2a9e30e4",
    game: "categories",
    pack: "chaos",
    prompt: "drugs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "fdde0541-c110-4bce-b300-0b2c82f8b3d6",
    game: "this_or_that",
    pack: "chaos",
    prompt: "whiskey or vodka",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "fe05a5fc-470a-4da7-8033-9ec5b3963eaf",
    game: "never_have_i_ever",
    pack: "chaos",
    prompt: "had sex on a sports field",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f0d6aa2f-52f3-49ca-9169-1ed9b5c73a13",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us who has the worst smelling junk",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "786a48f3-3c27-4939-9bbd-e094111fe158",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "blow smoke into the mouth of the person next to you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "fc1b38db-33b7-4810-be14-97da3187ccd1",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us who you think would rob a lemonaid stand",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "48f5f213-f0ea-42cb-ba14-7360662ad706",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us who you think has some nasty farts",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "0a909ba2-0b55-465a-a0ec-28d2d4a8ecbe",
    game: "do_or_drink",
    pack: "chaos",
    prompt: "tell us who you think has some nasty farts",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "baef052f-5202-4c79-994f-6211114f6300",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "pick the person to your left's nose, get a booger everyone else drinks",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both you",
    sipFlag: 2,
  },
  {
    uuid: "28385234-6f08-4557-a429-db56041ab3bc",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "inspect everyones nose and if you see any rogue hairs make them drink",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "0f0d7b70-f2a5-45ad-9728-45ada2457360",
    game: "do_or_drink",
    pack: "chaos",
    prompt:
      "tell us the story of how you lost your virginity, but you now have tourettes",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "b5666d9d-aa18-43fe-90e1-7297d5526c10",
    game: "wildcard",
    pack: "chaos",
    prompt: "call out everyone you've seen pick their nose and flick a booger",
    header: "GLHF",
    cardType: "GROUP",
    drinkHeader: "whoever drops it,",
    sipFlag: 2,
  },
  {
    uuid: "55bfe4cc-6ede-4be8-a891-bef85d582a1a",
    game: "wildcard",
    pack: "chaos",
    prompt: "if you are high right now",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: -1,
  },
  {
    uuid: "3055e8f8-a71e-4986-ab13-6c37f98526d5",
    game: "wildcard",
    pack: "chaos",
    prompt: "show us your best moonwalk",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "group votes if,",
    sipFlag: 1,
  },
];
