export default [
  {
    uuid: "0026cdb3-78ff-4738-8d39-31cf58513080",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "put hot sauce on everything",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "00523218-828c-4ffe-b0d5-382b3961143b",
    game: "wildcard",
    pack: "original",
    prompt: 'words that rhyme with "light"',
    header: "rhyme",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "018cc03a-8eb9-4ff9-9ace-5459419c0f1e",
    game: "categories",
    pack: "original",
    prompt: "insects that annoy you",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "026895d0-0f14-4b22-b979-80a2a8dd3cbf",
    game: "categories",
    pack: "original",
    prompt: "types of cheese",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "03427a33-db81-4a6b-a070-22933bb59a06",
    game: "do_or_drink",
    pack: "original",
    prompt:
      'let the group pick someone on your snapchat to say "i love you" to',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "039f6d7d-cb26-48a5-b28b-5a425e9290ce",
    game: "wildcard",
    pack: "original",
    prompt: "if you have had sex in your parents bedroom",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "06f387eb-b712-43fb-b088-5436825c12bd",
    game: "this_or_that",
    pack: "original",
    prompt: "be a bull fighter or be a lion tamer",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "08d26a2a-e61b-4fe7-857b-e1e97f67f3f0",
    game: "this_or_that",
    pack: "original",
    prompt: "eat 10 warheads at once or a california reaper pepper",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "0a543454-d5f4-4a87-b898-2facb6f31a2b",
    game: "this_or_that",
    pack: "original",
    prompt: "double headed shower or heated floors",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "0d759cdd-f1fa-49b1-9d34-218fa0f0bba9",
    game: "most_likely_to",
    pack: "original",
    prompt: "get shit on by the same bird twice",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "0d7e0e60-bc39-4297-881c-5dff4055fec8",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "gone skinny dipping",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "0ea4c270-3796-4726-8ee2-aa35c809638a",
    game: "wildcard",
    pack: "original",
    prompt: "start humming a song",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "first to identify,",
    sipFlag: -1,
  },
  {
    uuid: "10d447fb-457a-4d55-85d3-9c19ceb3f7df",
    game: "categories",
    pack: "original",
    prompt: "unisex names",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "10dee3d3-82b7-4cf2-a89c-3ddf8ff0f648",
    game: "do_or_drink",
    pack: "original",
    prompt: "tell us who you think is having a dry spell",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "13b51e3f-d265-4c3f-a154-5d2647cef168",
    game: "most_likely_to",
    pack: "original",
    prompt: "blackout on a weeknight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "19d61100-9479-47b7-b650-914024a64cfe",
    game: "this_or_that",
    pack: "original",
    prompt: "a dog that barks nonstop or one that chews on everything",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "1b4f4e02-44ab-4200-a168-63d31431bdd6",
    game: "categories",
    pack: "original",
    prompt: "female singers",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "1def64f9-5b66-40e2-88c2-730289c8d2c2",
    game: "this_or_that",
    pack: "original",
    prompt: "be a woman with manly legs or man with womanly arms",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "1e3dee82-d993-4392-8129-7cd2d62abdbf",
    game: "most_likely_to",
    pack: "original",
    prompt: "be drunk by the time everyone else wakes",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "1f72ec91-3b94-428a-8f2c-b32f294a7a3d",
    game: "do_or_drink",
    pack: "original",
    prompt:
      'serenade the group a rendition of "All I want for christmas is you"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "1ff8f442-2c8d-419d-977e-5046c342509c",
    game: "do_or_drink",
    pack: "original",
    prompt: "read the last set of text messages from your mom",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "251162b4-5a0f-417f-afc6-9a945593147b",
    game: "most_likely_to",
    pack: "original",
    prompt: "know a bit too much about childrens tv",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "25ab6a70-dc95-4c0f-a175-8c78c3cb2039",
    game: "most_likely_to",
    pack: "original",
    prompt: "play drinking games for pride instead of fun",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "25c944ec-6b39-43b2-803f-ed31a8f6481d",
    game: "categories",
    pack: "original",
    prompt: "chess pieces",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "26391aae-4790-4c42-87d5-7f414ebab46e",
    game: "this_or_that",
    pack: "original",
    prompt:
      "live in a country run by supermodels or on run by football palyers ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "27aac356-a67e-4c40-9b34-15c1c473add9",
    game: "most_likely_to",
    pack: "original",
    prompt: " not be wearing deoderant",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2864215c-ec8d-4983-997f-4a5075e85043",
    game: "this_or_that",
    pack: "original",
    prompt: "be as smart as you want or get laid whenever you want",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "2a5a8ab6-35a6-4d93-903c-4808e245f8a7",
    game: "most_likely_to",
    pack: "original",
    prompt: "invest months of effort into a costume",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2b81b03b-bab9-4ea7-a67a-ffb759581ce1",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "snuck out",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2d8a7ec2-55fd-497f-b9cc-1bfba240ac16",
    game: "most_likely_to",
    pack: "original",
    prompt: "order a round of shots",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "2fe59b1f-8881-4fc9-899c-c37510e3368a",
    game: "wildcard",
    pack: "original",
    prompt: "everyone that can touch your toes",
    header: "streeetch",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: -1,
  },
  {
    uuid: "30de42c0-eb01-4857-b0cc-6293d62ff7ad",
    game: "most_likely_to",
    pack: "original",
    prompt: "go ballistic over a board game",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "31ed3128-1fc7-47f9-bab4-224a26f15d3f",
    game: "most_likely_to",
    pack: "original",
    prompt: "plan a party then forget about it",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "3244d735-abd3-4cbd-90fc-abc2e428650e",
    game: "most_likely_to",
    pack: "original",
    prompt: "be confused, but nod along",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "3273677d-81b7-46b2-af6f-96aa9e2da3b9",
    game: "this_or_that",
    pack: "original",
    prompt:
      "write a novel that sells ok but is highly regarded or makes you rich but you're mocked for",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "336e3b7e-44fc-4a91-840a-5ea22adcb415",
    game: "this_or_that",
    pack: "original",
    prompt: "bar soap vs liquid soap",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "33ccaa50-cbe4-4ac6-b6c9-3f57a2b6e110",
    game: "this_or_that",
    pack: "original",
    prompt:
      "go to jail for a crime you didn't commit or hit and run a child but get away with it",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "344950fd-4ec6-4794-985f-2fbc12a33ed1",
    game: "wildcard",
    pack: "original",
    prompt: "anyone holding their phone ",
    header: "no phones",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "344e70e0-46ce-4094-acce-d3fdbecabc4f",
    game: "this_or_that",
    pack: "original",
    prompt: "be a cheater or be cheated on",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "348f08af-5f19-4d8e-9ac7-d51f65ebdc6f",
    game: "do_or_drink",
    pack: "original",
    prompt: "Everyone tell us who you are most attracted to here",
    header: "awweee",
    cardType: "GROUP",
    drinkHeader: "or, each ",
    sipFlag: 1,
  },
  {
    uuid: "34b8b893-910e-4147-8d09-34e0f0d03ef7",
    game: "this_or_that",
    pack: "original",
    prompt: "always have loose teeth or have a super fucked up smile",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "35b49250-6515-42c6-800b-ab3f134d1438",
    game: "most_likely_to",
    pack: "original",
    prompt: "sneak a water bottle of vodka into an amusement park",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "35dcdc6f-ebd0-42e5-a89e-8eb8d7b8d0d5",
    game: "most_likely_to",
    pack: "original",
    prompt: "put pineapple on their pizza",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "36673675-f2c8-4751-a8a2-ccb4a57c323b",
    game: "this_or_that",
    pack: "original",
    prompt: "take a parent to prom or your 12 yr old sibling",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "36eef467-8453-4581-b08e-6062aa5d49e2",
    game: "wildcard",
    pack: "original",
    prompt: "blue eyes",
    header: "eyecheck",
    cardType: "GROUP",
    drinkHeader: "the identified,",
    sipFlag: 1,
  },
  {
    uuid: "3aefa0a3-f6de-425b-92f6-93099564ad3f",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "dine and dashed",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "3b753825-35ea-4f29-8c87-bd9fc5a0f53d",
    game: "categories",
    pack: "original",
    prompt: "female actors",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "3d685492-c499-48c8-bee7-b16103ad7322",
    game: "this_or_that",
    pack: "original",
    prompt: "bang the person to your left or bang the person to your right",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "3d8e8f20-fb80-4da9-8a59-598cf879a1f0",
    game: "most_likely_to",
    pack: "original",
    prompt: "go viral on social media while blacked out",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "3f0ff774-e10d-4ce1-be2c-e50b2201d51d",
    game: "categories",
    pack: "original",
    prompt: "subjets in school",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "3f2db108-78ed-47cf-80d2-78b4f6a40b5f",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "threw up on a rollercoaster",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "42341623-e952-4057-945c-46bf2b08461d",
    game: "wildcard",
    pack: "original",
    prompt: "dudes ",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "42a23a44-30a2-419f-a9f7-f7c207e3fa14",
    game: "most_likely_to",
    pack: "original",
    prompt: "die first in a horror film",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "453032e7-32bb-4fb2-ac58-543f12229280",
    game: "wildcard",
    pack: "original",
    prompt: "everyone wearing red",
    header: "not red",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "47d4fbe1-ed16-45d5-a0bc-edcbb11af95c",
    game: "this_or_that",
    pack: "original",
    prompt: "lose both hands or lose your sex organs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "47e765f5-02ef-42ae-85b0-d98539085b82",
    game: "this_or_that",
    pack: "original",
    prompt: "fold or crumble toilet paper",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "49095415-dfcb-4b5f-a5ad-180d03dc5012",
    game: "this_or_that",
    pack: "original",
    prompt: "chicken nuggets or chicken fingers",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "49fc090a-9a8a-4450-accb-bec2c097239c",
    game: "this_or_that",
    pack: "original",
    prompt: "sweet or savory",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4d94d71a-c7e0-48b3-84ff-6a56a4fe51e9",
    game: "this_or_that",
    pack: "original",
    prompt: "only drink seltzers or twisted teas",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4e280246-6666-483d-a2c1-dc1618d379de",
    game: "this_or_that",
    pack: "original",
    prompt: "icecream cup or cone",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4fc58f37-de14-481c-8451-6ffa66398005",
    game: "categories",
    pack: "original",
    prompt: "appetizeres",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "5057eb67-80aa-40b4-a9a6-26a76e32a393",
    game: "this_or_that",
    pack: "original",
    prompt: "tied to the front of a helecopter or tied to the bow of a ship",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "50b7e222-5cfc-4bdc-b2f2-8e5c2a9b2a42",
    game: "most_likely_to",
    pack: "original",
    prompt: "ask their parents for drug money",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "5142dbb0-9814-4591-bc33-66317d5f4f25",
    game: "most_likely_to",
    pack: "original",
    prompt: "get ejected from an intermural kickball game",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "51b5f077-7105-4b8e-bf40-85ffc96e9654",
    game: "categories",
    pack: "original",
    prompt: "streaming services",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "5352502b-04be-4f37-b6ee-75767757034f",
    game: "this_or_that",
    pack: "original",
    prompt: "netflix or hulu",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "540fa0f1-3884-4512-9fa1-83e1c571fa61",
    game: "this_or_that",
    pack: "original",
    prompt: "be 5'2 or be 6'9",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "55cc4fb7-fbb7-4e86-a967-d7c166f546d4",
    game: "this_or_that",
    pack: "original",
    prompt: "flip phone or dial up internet",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "568b926a-a657-40bc-bd40-9991cfad56ed",
    game: "wildcard",
    pack: "original",
    prompt: "if you have caused a car accident",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "56b42660-2e4f-45ab-b420-c92d605284dc",
    game: "wildcard",
    pack: "original",
    prompt: "give us your best knock knock joke",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "56d24b35-ca4c-45a2-bae8-0ac5c074655c",
    game: "categories",
    pack: "original",
    prompt: "icecream flavors",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "58453b54-b7b7-4d38-b4ee-5b9a1d043f6b",
    game: "wildcard",
    pack: "original",
    prompt: "if you've read someones diary",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "59285d45-6d26-4d21-b862-8af0aef5e3fa",
    game: "wildcard",
    pack: "original",
    prompt: "name 5 types of light beer in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "593141b9-b90c-46db-9c84-75a68f3195ae",
    game: "categories",
    pack: "original",
    prompt: "things you put in the freezer",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "594a6192-fa80-48d6-a91c-eb69450e371f",
    game: "most_likely_to",
    pack: "original",
    prompt: "be scrolling on their phone at a party",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "5a67abc6-f2b4-46bf-9cde-5727d086a924",
    game: "this_or_that",
    pack: "original",
    prompt: "looks or personality",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "5d84f485-8c97-4b1a-913b-d581c6892785",
    game: "wildcard",
    pack: "original",
    prompt: "everyone who you've witness drunk drive ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the accused,",
    sipFlag: 1,
  },
  {
    uuid: "5e2dbc69-4b5c-40aa-bfdb-9b48d45107e2",
    game: "this_or_that",
    pack: "original",
    prompt:
      "severly bruise your tailbone every other month or have a stiff neck everyday",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "5e4649c8-a786-46e1-9e5f-9e1631aa438b",
    game: "wildcard",
    pack: "original",
    prompt: "if you have fantasied about someone here",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "5ed94e93-e625-4d87-9b55-9fb5e4f95ee6",
    game: "this_or_that",
    pack: "original",
    prompt: "have permenant canker sores or get paper cut every day",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "5fbb9c30-4a70-4b3b-a611-035faf76175c",
    game: "wildcard",
    pack: "original",
    prompt: "arm wrestle",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "5fda13f9-884d-432e-a744-32ed1b1082c1",
    game: "this_or_that",
    pack: "original",
    prompt: "tacos or burritos",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "604df63e-6e17-4288-9abb-ac3bea05f935",
    game: "this_or_that",
    pack: "original",
    prompt: "mcdonalds or chickfila",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "60c1d9ba-59f6-4997-ad25-e752e33bb48e",
    game: "wildcard",
    pack: "original",
    prompt:
      "call someone on speaker and have everyone bet on if they will answer",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "whoever's wrong",
    sipFlag: 2,
  },
  {
    uuid: "613ba5bb-1508-4eaa-9787-ae34a176cb96",
    game: "wildcard",
    pack: "original",
    prompt: "anyone single ",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "62dee3d7-731b-43d9-a45f-9027852b071d",
    game: "categories",
    pack: "original",
    prompt: "things you bring camping",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "635f4155-d369-4c93-8da5-9e572bdb6224",
    game: "this_or_that",
    pack: "original",
    prompt: "have one eye brow or have no eyebrows",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "64e1a534-9eae-4c99-86c7-644f9dc0d02c",
    game: "this_or_that",
    pack: "original",
    prompt:
      "spend the rest of your life within a 5 mile radius or never sleep in the same place twice",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "668b8b51-0f63-409f-a67e-8ae6a3590066",
    game: "most_likely_to",
    pack: "original",
    prompt: "be the only one laughing at their own joke",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6b2673f6-977f-4374-801e-6f9c4cd81e18",
    game: "categories",
    pack: "original",
    prompt: "songs by the beatles",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "6b364349-0c14-481f-ba69-97d0ff545b23",
    game: "most_likely_to",
    pack: "original",
    prompt: "to get lost while drunk",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6c7d2298-7fc9-4c4d-8b21-c2b323402ceb",
    game: "this_or_that",
    pack: "original",
    prompt: "punch your child or punch your mother",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "6c9a3563-10c0-45a3-8f14-eb5026a0ecec",
    game: "most_likely_to",
    pack: "original",
    prompt: "have a new job every week",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6d284238-0c28-4602-9aff-75d1a299da2e",
    game: "this_or_that",
    pack: "original",
    prompt:
      "be a massive dumbass in public once or make 50 stupid mistakes ony you know about",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "6d8d87ab-b25a-4bd9-9a8e-1b470e4d5643",
    game: "this_or_that",
    pack: "original",
    prompt: "look 60 at 20 or look 10 at 40",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "6dec7932-7794-46fd-b193-3e13c83310f4",
    game: "wildcard",
    pack: "original",
    prompt: "Eveyone put your phone in the center",
    header: "Busy Bee",
    cardType: "GROUP",
    drinkHeader: "first notified,",
    sipFlag: 1,
  },
  {
    uuid: "6e0ce30e-e0b1-465f-a8d4-858a4323470e",
    game: "most_likely_to",
    pack: "original",
    prompt: "buy a keg for a casual get together",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "6ea59b1d-09f2-4e46-8147-446c32f169a5",
    game: "do_or_drink",
    pack: "original",
    prompt: "swap shoes with the person to your left",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "6f0bce1e-3ca5-4834-b2ba-342def3f981a",
    game: "categories",
    pack: "original",
    prompt: "languages",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "72b8452c-6d0c-47c8-ae2b-5c3342842e55",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "bought a pair of sunglasses over 300$",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "7408242d-2373-4d05-8112-3fd84045f90d",
    game: "this_or_that",
    pack: "original",
    prompt: "see the future or change the past",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "74bb7972-c36f-41f3-a17f-e6175739dcdc",
    game: "this_or_that",
    pack: "original",
    prompt: "hot dogs or hamburgers",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "774d72d1-4582-4347-adc6-39784820620d",
    game: "categories",
    pack: "original",
    prompt: "dog breeds",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "776a6521-4628-4de7-abad-7bca9018d514",
    game: "most_likely_to",
    pack: "original",
    prompt: "be overly excited about kareoke ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "78813825-4ae0-42bd-8851-dc503cf19368",
    game: "most_likely_to",
    pack: "original",
    prompt: "hook up and forget their name",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "79244120-afa2-4892-86b3-9d52e0fbfd63",
    game: "categories",
    pack: "original",
    prompt: "viral internet challenges",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "7a4aa1be-bfab-4999-aeed-2614d2e1eff5",
    game: "categories",
    pack: "original",
    prompt: "desserts",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "7a61658b-1628-4334-9e4c-2fa23c71e3e4",
    game: "wildcard",
    pack: "original",
    prompt: "brown eyes",
    header: "eye check",
    cardType: "GROUP",
    drinkHeader: "the identified,",
    sipFlag: 1,
  },
  {
    uuid: "7d0d21c8-00e1-448f-9130-157234f9de89",
    game: "categories",
    pack: "original",
    prompt: "types of dance moves",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "7d766bb4-3307-4b72-a3d3-e9c1f0173951",
    game: "most_likely_to",
    pack: "original",
    prompt: "laugh without understanding the joke",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "7d8060c7-2e1f-4cee-a4c9-0ee78e983930",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "been in a band",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "7e0faceb-7a5e-4601-b6f1-cfbb39e973fa",
    game: "wildcard",
    pack: "original",
    prompt: "everyone reveal the highest ticket they've paid",
    header: "bankrupt",
    cardType: "GROUP",
    drinkHeader: "the highest,",
    sipFlag: 1,
  },
  {
    uuid: "8085f61d-820b-4b1d-8110-3e546c4c3bfc",
    game: "most_likely_to",
    pack: "original",
    prompt: "trample a small child on black friday with no remorse",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "80eeaead-ce12-4a73-9dac-bdc2c0fcc357",
    game: "most_likely_to",
    pack: "original",
    prompt: "have a second family",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8121acf3-83a4-4c4a-8556-4f209595933b",
    game: "this_or_that",
    pack: "original",
    prompt: "have to always wear diapers or always drink from a baby bottle",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "82e70e39-64f5-4aeb-9a76-006c1b804c0d",
    game: "most_likely_to",
    pack: "original",
    prompt: "name their pet after a transformer",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "84951fc0-684d-463e-87a8-d9c09333c743",
    game: "this_or_that",
    pack: "original",
    prompt: "pancakes or waffles",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "87b8df4a-1688-40f3-834b-9f45acbdbca8",
    game: "wildcard",
    pack: "original",
    prompt: "thumb war",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "886a7ae8-ae0b-4792-a6be-209baafcfcba",
    game: "categories",
    pack: "original",
    prompt: "animals to keep as pets",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "88783c8b-cc95-4b34-a7f4-ffae49881ee1",
    game: "most_likely_to",
    pack: "original",
    prompt: "have a stuffed animal they secretly cuddle with",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "88b33b0f-5222-46df-b274-a7a90d638b4e",
    game: "wildcard",
    pack: "original",
    prompt: 'first to solve "13x=39"',
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "8a0285dd-6caf-4b7a-bfde-b5a8c642329e",
    game: "most_likely_to",
    pack: "original",
    prompt: "have a terrible diet but always be skinny",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8b046323-f971-4940-921f-fef6bde53c1b",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "been on crutches",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "8b265492-a9c1-481f-8ce0-c26340ff6f14",
    game: "most_likely_to",
    pack: "original",
    prompt: "have over 40 hours of screen time",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8b8e6647-180d-49d8-ba7a-059090fa8d8a",
    game: "most_likely_to",
    pack: "original",
    prompt: "pick up a hitchhiker",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8c6dadc8-d1a8-43e3-9cf6-dc9a10c727ab",
    game: "categories",
    pack: "original",
    prompt: "country bands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "8d354f3a-bd3f-4645-ae74-a660844521db",
    game: "most_likely_to",
    pack: "original",
    prompt: "show up for a party on the wrong day",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "8d7180a7-14f6-4f62-8b8e-bd8033f920b2",
    game: "categories",
    pack: "original",
    prompt: "board games",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "8f4dbb51-44bd-4a1b-adc1-f73a77e281a4",
    game: "this_or_that",
    pack: "original",
    prompt: "mexican food or asian food",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "8f9b2893-a13b-4746-8394-9143517208df",
    game: "do_or_drink",
    pack: "original",
    prompt: "sexy crawl on the floor toward a player of your choice",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "8ff32265-27d9-4fee-a0bd-397d5819b32b",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "lied about my age",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "905b99c5-1e86-42d4-95ac-1483d069a306",
    game: "most_likely_to",
    pack: "original",
    prompt: "dodge a drink ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "909c6b91-ba5b-47fa-be15-cd0edd7efbf4",
    game: "wildcard",
    pack: "original",
    prompt: "ladies ",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "919f8b3d-79f6-4642-931b-904c36d439e9",
    game: "wildcard",
    pack: "original",
    prompt: "Anyone whose phone is under 50% ",
    header: "dead",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "91b2fc16-4a1e-4254-886d-a95b8f3adb4c",
    game: "this_or_that",
    pack: "original",
    prompt: "lose the ability to speak for a year or walk for a year",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "924c42be-fa66-47fa-878e-df7306b669a5",
    game: "wildcard",
    pack: "original",
    prompt: "pick who would be the best partner in the Amazing Race",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "both of you,",
    sipFlag: -1,
  },
  {
    uuid: "93d5d9b3-6775-4a59-9435-51f2c427c16a",
    game: "this_or_that",
    pack: "original",
    prompt: "constant dry eyes or runny nose",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "94c0ddfd-f6c1-4b5c-ab26-06614d8f14f0",
    game: "wildcard",
    pack: "original",
    prompt: "everyone wearing  an earing",
    header: "be jewled",
    cardType: "GROUP",
    drinkHeader: "the fashionable,",
    sipFlag: 1,
  },
  {
    uuid: "94d075a5-1278-4a91-8c7b-5ae72d074fe0",
    game: "most_likely_to",
    pack: "original",
    prompt: "be the biggest alcoholic",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "95e167b7-e859-4f2a-bd7a-63e0f88ae21d",
    game: "this_or_that",
    pack: "original",
    prompt: "see an avalachance coming at you or a tsumani",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "97a76bd5-246e-43c7-bc31-1e9f48a9a1be",
    game: "most_likely_to",
    pack: "original",
    prompt: "heat up their milk ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "98bb5124-d18f-4238-a7e2-780b9c40bf2f",
    game: "most_likely_to",
    pack: "original",
    prompt: "fail their new years resolution by the end of january",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "99391ebb-d799-4426-b291-3230961358cc",
    game: "this_or_that",
    pack: "original",
    prompt:
      "get free gas for 3 years or be exempt from speeding tickets forever",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "9ac7576a-2cd3-4637-b01e-4d2e2fac9cc4",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "changed a diaper",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "9b1f957b-ba5f-47c5-9405-310af434a3b8",
    game: "categories",
    pack: "original",
    prompt: "countries in europe",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "9b3a438a-4d14-4282-b2b7-7f7905877ab9",
    game: "wildcard",
    pack: "original",
    prompt: "whoever has the most unread messages ",
    header: "ignorer",
    cardType: "GROUP",
    drinkHeader: "the ignorer,",
    sipFlag: 1,
  },
  {
    uuid: "9ca6602f-7fd9-4454-9c33-f632034ba2fb",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "gotten arrested ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "9ed1194c-042e-42f1-a6d8-bed9451c5fc7",
    game: "categories",
    pack: "original",
    prompt: "rappers",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "9f0a8a8e-70d0-4daa-b564-7bc310b40c6f",
    game: "most_likely_to",
    pack: "original",
    prompt: "make other people try new beer before ordering it themselves",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a030b632-0a5f-46d9-ad8d-590b23eaee90",
    game: "this_or_that",
    pack: "original",
    prompt: "30 good friends or 3 super close friends",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "a1fb3217-76be-4e67-a9b0-1bbe417d4eed",
    game: "most_likely_to",
    pack: "original",
    prompt: "buy follwers ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a57607df-8ace-44d3-93fd-c4f5e687f80b",
    game: "this_or_that",
    pack: "original",
    prompt: "get a paper cut between your fingers or get slapped 50 times",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "a759a56e-0c05-49e3-89a9-5bfbc4e50cba",
    game: "this_or_that",
    pack: "original",
    prompt: "airline food or hospital food ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "a7b2b955-aa45-498b-8afd-6cace76a526e",
    game: "most_likely_to",
    pack: "original",
    prompt: "become addicted to meth",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "a836b563-0fa3-4ebe-924f-69a3bd999d5e",
    game: "categories",
    pack: "original",
    prompt: "alcoholic drinks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "a982b863-226f-4bfa-9d62-f373a825eaf8",
    game: "this_or_that",
    pack: "original",
    prompt: "always be barefoot or always keep your shoes on",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "ac3d6f51-d144-4663-af70-3b3829b7300c",
    game: "this_or_that",
    pack: "original",
    prompt: "clean up poop or clean up vomit",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "ae787f31-0465-49ab-9aa3-0ce206208a6b",
    game: "wildcard",
    pack: "original",
    prompt: "rock, paper, scissors",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "af54aeec-fcfd-4aa9-8a62-82ad2f8ad7f1",
    game: "this_or_that",
    pack: "original",
    prompt: "have a wrinkly face or a saggy body",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "b29c3945-6009-4848-aff3-1965d27ef258",
    game: "categories",
    pack: "original",
    prompt: "activities old people do",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "b328d64b-9a53-4878-8e98-d73a71ac6d04",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "made money in crypto",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "b6b65825-68a4-4e4f-ab21-5ac11c6d6ea0",
    game: "categories",
    pack: "original",
    prompt: "minimum wage jobs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "b7831be0-6cde-4abe-b070-663b09672ae2",
    game: "wildcard",
    pack: "original",
    prompt:
      "race to text to the host \"timmy took a turtle to tim's toddler's target party!\"",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "first to send",
    sipFlag: -1,
  },
  {
    uuid: "b79fc662-476c-4691-9c0e-6ba60c390982",
    game: "most_likely_to",
    pack: "original",
    prompt: "flirt with a grandma/pa",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "b8fa56a8-6653-4c77-b850-93e833a2071a",
    game: "wildcard",
    pack: "original",
    prompt: "race to name 3 countries starting with E",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "ba0272bc-dcd0-49f8-808e-cf56a7f134d1",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "lied on my tinder profile",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "bb194257-44f1-489d-93d7-838364922e4d",
    game: "this_or_that",
    pack: "original",
    prompt: "uber or lyft",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "bc008e30-cbf5-4ecc-b096-aee693846615",
    game: "most_likely_to",
    pack: "original",
    prompt: "brag about something stupid",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "bc6b0d49-b041-42d8-890d-d93c08f0f89f",
    game: "this_or_that",
    pack: "original",
    prompt:
      "have everything you think displayed above you or have everything you do be live streamed ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "bccef639-0904-4eb9-8dee-bb6cdffc4753",
    game: "most_likely_to",
    pack: "original",
    prompt: "be a shit cook",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "be64405d-611c-449c-90fa-0dcecc8538f2",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "participated in a beer olympics",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "bf830d92-5f2f-43bb-911a-8dffd6f0336b",
    game: "most_likely_to",
    pack: "original",
    prompt: "cause a natural disaster with their body odor",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "bfdc6992-43e3-4252-a173-f2eb10ea0297",
    game: "most_likely_to",
    pack: "original",
    prompt: "leave the stove on, cause a fire, and sleep through it",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "c0cf21e0-a06e-406e-a070-30d3fba13a9b",
    game: "categories",
    pack: "original",
    prompt: "rock bands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "c26fea29-e263-473f-9f05-a98211d18c06",
    game: "this_or_that",
    pack: "original",
    prompt: "box mike tyson or 4 people in this room",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "c2bcf8a7-5451-4160-af15-8c5eccce0802",
    game: "most_likely_to",
    pack: "original",
    prompt: "say they hate small talk during small talk",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "c38147ee-2e5f-4c0a-8ed6-8f4ef0c8a247",
    game: "this_or_that",
    pack: "original",
    prompt: "have a snake infested bathroom or rat infested kitchen",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "c45846d7-c79c-44c0-8d86-99c31162694f",
    game: "most_likely_to",
    pack: "original",
    prompt: "cancel plans at the last minute",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "c566484a-4b9c-4255-a12a-92ddbc9dddff",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "farted and blamed the dog",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "c5e4fa92-646c-46a6-808a-8e2b88ae56d5",
    game: "categories",
    pack: "original",
    prompt: "cereal brands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "c606c9ba-262c-4a52-b55a-386cfc94ad88",
    game: "categories",
    pack: "original",
    prompt: "cartoon characters",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "c6f7cda9-2a7c-4273-987b-34c3adfc9bb9",
    game: "wildcard",
    pack: "original",
    prompt: "name 3 icecream flavors in 5 seconds, GO",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "c8dd8d28-6d24-45f7-abfa-6498e3583056",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "meditated for over an hour",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "c999d77f-891f-446f-96c3-a91a08bb0265",
    game: "most_likely_to",
    pack: "original",
    prompt: "get scammed for all their money in a foreign country",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "ca15a9ab-e2af-4108-b853-a75f94c04e06",
    game: "categories",
    pack: "original",
    prompt: "restaurants",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "cad92794-2e0b-4c1e-a496-78777b2d6c53",
    game: "wildcard",
    pack: "original",
    prompt: "whoever has the most followers on any one platform",
    header: "count check",
    cardType: "GROUP",
    drinkHeader: "the most,",
    sipFlag: -1,
  },
  {
    uuid: "cb18c975-af06-4c54-8fb6-125255f8f419",
    game: "never_have_i_ever",
    pack: "original",
    prompt: 'said "I Love you" but didn\'t mean it',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "cd884613-6c26-40b5-8973-3a2ef1766780",
    game: "categories",
    pack: "original",
    prompt: "states where weed is legal",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "ce2f3193-e7c9-4e9c-a304-400ccd62ba62",
    game: "categories",
    pack: "original",
    prompt: "sneaker brands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "cf65df38-a41b-476b-b2c9-044ba12aa927",
    game: "this_or_that",
    pack: "original",
    prompt:
      "fall down 20 wood steps naked or 40 concrete steps in football gear",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "d18e60c5-1f16-4db5-b77f-b6261b0ff078",
    game: "wildcard",
    pack: "original",
    prompt: "Anyone who had a myspace or AIM account",
    header: "old skool",
    cardType: "GROUP",
    drinkHeader: " old peeps,",
    sipFlag: 1,
  },
  {
    uuid: "d2e5f5a1-1315-4fa9-b518-6c5ca181d91a",
    game: "most_likely_to",
    pack: "original",
    prompt: "overeat and then be hungry in an hour",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d3019c4c-73e9-4db0-872f-89d8a292aad7",
    game: "most_likely_to",
    pack: "original",
    prompt: "apoligize for not doing anything wrong",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d4189f70-68c8-4698-b51b-6211368ee428",
    game: "wildcard",
    pack: "original",
    prompt: "name all 12 zodiac signs",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "d41f7bf4-427d-4e4a-bfc2-6d7a196ca6cd",
    game: "categories",
    pack: "original",
    prompt: "water cooler topics",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "d5dca17f-9c18-409c-81b5-8b25f38105b9",
    game: "most_likely_to",
    pack: "original",
    prompt: "take the last slice of pizza",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "d6fa22bf-edaa-4aae-822b-b978398079c1",
    game: "categories",
    pack: "original",
    prompt: "religions",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "d75a45bb-45d4-47b1-a56b-2d4cdcccb904",
    game: "this_or_that",
    pack: "original",
    prompt: "wake up at 4am every day or go to sleep at 4am every night",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "d99caec2-c6e3-43c0-9602-41e96a8fd3a9",
    game: "this_or_that",
    pack: "original",
    prompt: "always be stuck in traffic or always have bad internet",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "da362544-77a8-42f1-952c-e2c898f08577",
    game: "categories",
    pack: "original",
    prompt: "places starting with the letter F",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "db48a9ef-5c7b-4dfd-a817-d99d03852963",
    game: "categories",
    pack: "original",
    prompt: "snacks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "de96060d-17c4-4dbf-adcc-dfeb1919d34e",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "posted a youtube video",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e05aa7d6-a53e-4551-83d6-0239ca04c322",
    game: "this_or_that",
    pack: "original",
    prompt: "have super extroverted parents or super strict parents",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "e06a1357-da34-4082-a1c6-bd315f11b3c1",
    game: "this_or_that",
    pack: "original",
    prompt: "swamp ass or itchy butthole",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "e0779d0e-061c-4e62-a2c0-3cbf0b7ca3ad",
    game: "categories",
    pack: "original",
    prompt: "brunch foods",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "e16fc27d-e76c-4d6c-b09b-49de9727450d",
    game: "this_or_that",
    pack: "original",
    prompt: "have one nipple or have 2 belly buttons",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "e24fd4df-c333-4ac4-888f-d19164d5fa6b",
    game: "categories",
    pack: "original",
    prompt: "things you call your grandmother",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "e2574bd9-b4cd-42c6-91b6-0c3843d0ba52",
    game: "most_likely_to",
    pack: "original",
    prompt: "be the most indecisive",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "e32761f5-778d-411c-8d8e-01b04c9215d9",
    game: "this_or_that",
    pack: "original",
    prompt: "see everything blurry or see only black and white",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "e5fd23f4-8722-4af0-bdad-fb69118ea113",
    game: "categories",
    pack: "original",
    prompt: "errogenous zones ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "e6821543-c5e8-43b6-aa56-4e24f215bd1f",
    game: "most_likely_to",
    pack: "original",
    prompt: "end up in a pyramid scheme",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "e6fbfd1a-400a-4570-85fb-ecb755b22d33",
    game: "categories",
    pack: "original",
    prompt: "names starting with J",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "e7b45288-255a-477c-99b8-f6bd18c87869",
    game: "categories",
    pack: "original",
    prompt: "types of soda",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "e88346e3-a670-4aed-a874-27d4e7c70d81",
    game: "most_likely_to",
    pack: "original",
    prompt: "start a drunken arugment with someone twice their size",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "e9c2fcff-453f-468b-89a9-2729a695c5e2",
    game: "wildcard",
    pack: "original",
    prompt: "whoever has the biggest forehead",
    header: "Peyton Manning Penalty",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "ea938531-7f76-4ff6-9f6c-ea8e2d6eacdc",
    game: "most_likely_to",
    pack: "original",
    prompt: "get in trouble for saying the n word",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1,
  },
  {
    uuid: "eb380c66-2518-4e50-b8b0-8d704b39bd9f",
    game: "categories",
    pack: "original",
    prompt: "fast food spots",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "ebffb7fc-16c1-4770-ba94-50b36e16ae81",
    game: "wildcard",
    pack: "original",
    prompt: "for every year you've been in a relationship",
    header: "committed",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "ec6e700c-4d9b-4945-8d1b-ba0e429c9681",
    game: "this_or_that",
    pack: "original",
    prompt: "pepsi or coke",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "ec852de6-ba00-4e3b-bb75-86034ae99fbf",
    game: "wildcard",
    pack: "original",
    prompt: "check your screen time",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the longest,",
    sipFlag: 1,
  },
  {
    uuid: "eef6fed1-06fb-45fe-9670-5e5e1ff1d981",
    game: "categories",
    pack: "original",
    prompt: "movies with The Rock in them",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "efcf34ea-604f-47d3-a41a-43d31d387525",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "shoplifted",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f0b5a252-a371-4487-a0c9-ae99caeee4c5",
    game: "wildcard",
    pack: "original",
    prompt: "lead the group in Simon says",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "f0c78a0f-a878-4bfa-afc6-a05b12b914b4",
    game: "this_or_that",
    pack: "original",
    prompt: "marry a complainer or marry a bully ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "f1df952d-bce1-422e-a963-23b8b9e8ba4c",
    game: "this_or_that",
    pack: "original",
    prompt: "crunchy peanut butter or smooth peanut butter",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "f22e9acf-4cf4-49b3-a665-71ca3facc0b9",
    game: "never_have_i_ever",
    pack: "original",
    prompt: "fainted in public",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f4ec5c01-68c2-424a-9168-996d3c67e240",
    game: "categories",
    pack: "original",
    prompt: "astrological signs, if you get them all everyone is safe!",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "f7db78cc-4ace-491b-b4c5-0590b0cc93ae",
    game: "wildcard",
    pack: "original",
    prompt: "Everyone wearing a watch ",
    header: "Time Check",
    cardType: "GROUP",
    drinkHeader: "if you are,",
    sipFlag: 1,
  },
  {
    uuid: "f86141fd-bc84-4811-8f29-8d6b07bd3a08",
    game: "this_or_that",
    pack: "original",
    prompt: "be able to read minds or be able to fly",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "f936e93f-4fe7-4825-8395-c5b1d8360ce3",
    game: "this_or_that",
    pack: "original",
    prompt: "steal money from a friend or cheat with thier partner",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "fa3f5646-bdda-4c41-b1d6-5effea753670",
    game: "wildcard",
    pack: "original",
    prompt: "Everyone who had coffee this morning",
    header: "caffinated",
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "ff979bd2-fff7-400f-bdbb-01de54d00bd3",
    game: "wildcard",
    pack: "original",
    prompt: "Anyone who has their toes out right now",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the gross,",
    sipFlag: 1,
  },
  {
    uuid: "1efec65c-8e46-4b07-a921-ced81a96c3a1",
    game: "wildcard",
    pack: "original",
    prompt: "anyone with the same name",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "5728f1f0-e8e3-4584-830f-edbc1469e684",
    game: "wildcard",
    pack: "original",
    prompt: "if you have a diary",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "ddc05057-c78e-4560-aa02-8bcab45aecad",
    game: "wildcard",
    pack: "original",
    prompt: "list 5 names starting with P in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "win and,",
    sipFlag: -1,
  },
  {
    uuid: "b68eeeb1-0581-4e35-b5ce-44715cd1ca44",
    game: "wildcard",
    pack: "original",
    prompt: "pick someone to take a sip with you ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 0,
  },
  {
    uuid: "8b45a5a0-9cbb-45b2-9836-90399a3a5e77",
    game: "wildcard",
    pack: "original",
    prompt: "pick two people to take a sip ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 0,
  },
  {
    uuid: "f3acdbc0-4dc6-4664-b363-f18d1e98c9aa",
    game: "wildcard",
    pack: "original",
    prompt: "rhyme 3 words with doctor in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "win and,",
    sipFlag: -1,
  },
  {
    uuid: "8844fa07-57a7-4368-ad2c-dcbd9c7871f9",
    game: "wildcard",
    pack: "original",
    prompt: "name 5 types candy flavors in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "win and,",
    sipFlag: -1,
  },
  {
    uuid: "7b10760d-ab63-438b-8704-57975115953e",
    game: "wildcard",
    pack: "original",
    prompt: "if you are married ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "70d6c93a-ab61-4239-919b-feb088a65d7e",
    game: "wildcard",
    pack: "original",
    prompt: "drink for each sibling you have",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 0,
  },
  {
    uuid: "428be92a-26c6-46e7-9253-08aa91fa3737",
    game: "wildcard",
    pack: "original",
    prompt: "if your ring finger is longer than your index finger",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "613eeb1c-5585-48bb-a806-2419377bbf74",
    game: "wildcard",
    pack: "original",
    prompt: "tell us the last names of the two people next to you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "win and,",
    sipFlag: -1,
  },
  {
    uuid: "bdcf6715-bb47-45c1-bc55-fdfb868ba1ba",
    game: "wildcard",
    pack: "original",
    prompt: "tell us the middle names of any two people here",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "win and,",
    sipFlag: -1,
  },
];
