export default [
  {
    uuid: "38756411-1ace-4d13-92d1-4945eb29a503",
    game: "categories",
    pack: "girlsnight",
    prompt: "perfume brands",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "da0db516-3d33-43ca-8ada-66e058f1dd84",
    game: "categories",
    pack: "girlsnight",
    prompt: "mysoginistic men",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "bd50cc71-33e6-4151-bfa2-291ce5ee7f2f",
    game: "categories",
    pack: "girlsnight",
    prompt: "worst guy names",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "67c7d57d-1148-4097-8965-24e7f5bde515",
    game: "categories",
    pack: "girlsnight",
    prompt: "things that give you the ick",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "bcba061a-166d-4aca-a1f4-4f77c40986a2",
    game: "categories",
    pack: "girlsnight",
    prompt: "types of womens clothing",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "bf222d93-113b-4399-a03e-b604553ce12d",
    game: "categories",
    pack: "girlsnight",
    prompt: "types of make up",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "b272d53a-25ee-40e3-acf0-d2a5461db3a4",
    game: "categories",
    pack: "girlsnight",
    prompt: "TV shows with love in the name",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "32fa0d73-1c96-4605-b3f5-3b1f1f144b4b",
    game: "categories",
    pack: "girlsnight",
    prompt: "reality TV shows",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "626ce648-5e12-4832-8ced-20770026db5c",
    game: "categories",
    pack: "girlsnight",
    prompt: "muscles",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "8d41123e-3411-4a7b-8d95-31a4a651085e",
    game: "categories",
    pack: "girlsnight",
    prompt: "songs by beyonce",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "51ca9c52-9a65-4400-b5e8-ebf2e4b6a46a",
    game: "categories",
    pack: "girlsnight",
    prompt: "synonym for dick",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "f7ee6774-83f4-4f1e-bc06-9f5b21870f60",
    game: "categories",
    pack: "girlsnight",
    prompt: "famous influencers",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "8130815c-e438-4036-b406-ec400580fd37",
    game: "categories",
    pack: "girlsnight",
    prompt: "ways to deny a guy out in public",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "1e61798c-4609-49e6-afca-b9baba62f526",
    game: "categories",
    pack: "girlsnight",
    prompt: "reasons to get of sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "da2cdfb3-145b-40da-9b47-c5507f7a18ec",
    game: "categories",
    pack: "girlsnight",
    prompt: "wines",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "31128c21-7146-4a0c-a816-894c43466458",
    game: "categories",
    pack: "girlsnight",
    prompt: "spices",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "12ad3180-cde0-4e91-93d1-ef005596fb14",
    game: "categories",
    pack: "girlsnight",
    prompt: "demi levato songs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "23530481-b6e4-4f10-bc85-504db302a7ee",
    game: "categories",
    pack: "girlsnight",
    prompt: "things in your purse",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "1669813f-5289-4b24-b814-1909353f9f01",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "each of you demonstrate giving a blowjob",
    header: "class",
    cardType: "GROUP",
    drinkHeader: "refuse and,",
    sipFlag: 2.0,
  },
  {
    uuid: "9403db63-249b-4377-8838-8aa31b705f9e",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: 'post a pic saying "Horny and lonely, DM me"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "c49d1ceb-9a80-4403-8b9a-ab4649c4f702",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt:
      "let the person next to you send an eggplant emoji to the anyone they want",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "6592018a-0da1-4aae-9e86-44d219750691",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "call a pizza place and ask to make a vagina shaped pizza",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "dfda0169-b776-49ef-a3fc-bc737681bb16",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "reenact rejecting a guy because of his height",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "b87cc0be-2af4-4472-b16b-20b6acc26d25",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "let the group pick someone on your snap chat to send a pic of you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 2.0,
  },
  {
    uuid: "e2fbf9a5-af99-4a27-b5bd-28d893c258fd",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "tell the group how you were toxic in your last relationship",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "68972975-0598-4303-9094-44669bf01881",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "go on a dating app and invite over the next person you match with",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 2.0,
  },
  {
    uuid: "d54c4630-a0fa-4052-b0d8-39effc1d62a9",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "tell the group who your last hookup was",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "f18ba918-5f48-41c6-b03a-652b30a19082",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt:
      "using your hands, approximate the biggest penis you've seen in person",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "da761f04-7910-4c48-8e56-d04913e47afb",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "tell us who you would not let watch your child",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "47a523a4-9947-4c34-a994-093cefa89527",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "tell us who you would not leave alone with your brother",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "0efcc807-0e14-4f15-adda-bc23273d75d9",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt:
      "using your hands, approximate the smallest penis you've seen in person",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "8a0e9e87-98dc-4a27-9460-0be04e84b5b1",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt:
      "let the person to your right open instagram, pick a person, and like all of their pictures for the last year",
    header: "likes",
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "1126e6c1-e047-4ec7-bdf8-8d0bfe4bc75d",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "give a demonstration of a rim job on an empty bottle",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 2.0,
  },
  {
    uuid: "c62978fe-3abe-49fa-86f5-f399f901db53",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: 'DM your crush "wyd rn"',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 2.0,
  },
  {
    uuid: "67b75ab5-12e1-4d91-8fb0-64edd7c87178",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: 'open the door and yell "I LOVE ANAL" ',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "e4cb6267-f38d-4301-855d-b7e31e5a0bff",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "post a thirst trap ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "a4211aaa-5778-4c8d-9da7-6a741212f889",
    game: "do_or_drink",
    pack: "girlsnight",
    prompt: "list off your sexual partners",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 3.0,
  },
  {
    uuid: "044b52e3-2b9f-498b-ab9f-bf2edb0edaa8",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he iceskates",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "5ed6549b-3180-44c0-9244-1077d56a1c01",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "his feet dont reach the ground on a bar stool",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "3d97bae8-0c03-4018-804f-4e05962568e5",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: 'hes under 6"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "808b105b-c1d8-45d8-8a31-88837ff42cd5",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he has jr in their name or IS JUNIOR",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "48755bb7-1970-4390-87f2-76e5b7ab7732",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he dosent like dogs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "76aa3e82-a6bd-414c-86e3-da2259ab8d70",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "hes a golden retriever boyfriend",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "95223ba5-8bfd-4a43-b59e-f521a7b8390a",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he travels for work",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "45f26aec-5d6b-479d-b0b9-0b838e7bdf28",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he licks his fingers after eating cheetos",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "8bd50c65-13b0-467b-bec4-9c50d91a172e",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he uses an ipad",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "e7e5b0a1-5d80-4940-9678-bd97beb4d920",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: 'says "smile for me"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "c1ba3e55-e61d-46cd-a687-7e599822dc67",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he wears skinny jeans",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "a1980378-596d-4140-a037-89916369d5dd",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he has a lion tatoo",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "e9f28bf2-3cbd-4b9a-b1c5-411e0da0cea5",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he has a high snap score",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "98c2d335-9c2b-44f1-a040-b9c16a793d4f",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he wears cargo shorts ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "f462749c-9ae3-4bf4-98ab-c0fbf7acdd7f",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he cries in front of you",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "1782112e-71f0-4a16-9e1e-5d5be109334e",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he wears ankle socks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "5518d056-0113-4a54-97e6-90a7d998a282",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he drinks from a straw",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2caa80d2-26f2-4676-be94-4f81eb9d870e",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he always tries to run in water",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "42aecd28-f542-4e7e-9b3e-88d8515b182c",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he ties his hoodie around his waist",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "9461bb47-a70c-4996-8a39-000fce54a443",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he has a velcro wallet ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "b9017246-4d0d-4e18-84e7-123360b02b72",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he warmups up before exercise",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "04422fb5-d04b-4382-b054-c5dc1b7ce765",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "you see him running for a bus",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2b0d2292-a0d4-4c74-b2f6-67f663d73199",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he finishes every sentence with lol",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2363821a-5605-4243-8ed1-716e8a70885f",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he vapes ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "76cc7585-f59a-493e-a8af-923615ec4360",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he drinks straight milk",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "51b379f5-9083-41b2-aa53-142a28094a78",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he gets mad at a game",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2a53f734-7b12-4b5c-a6f1-c669928baa55",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he asks you to split the bill",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "6e9826ea-3f1a-495f-95a9-f6ea6bae25ba",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "you find out hes into NFTs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "934ba7ff-05fc-4d1e-ba65-303cdf50df66",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he flinches during a every horror movie",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "7d12f6c9-956d-4dda-adee-7300ee7a3e42",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he uses his own back scratcher",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2583748e-283c-49ad-a243-ac79a9251286",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "hes into legos",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "7346e2ef-8db6-4348-a15f-077971acf649",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he dosen't use punctuation",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "cff48ad9-061e-4de4-bd31-cf98fcffca04",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "wears goggles to swim",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "1ac4c400-21af-4a75-8583-c801a8a81122",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "calls girls females ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "029ab74d-883a-4038-b319-22d927a65ada",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "has a lunch box",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "a0f14f84-826c-4304-b554-1b66915cb530",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he jumps around the air matress to deflate it",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "f73c2b6c-b286-4b5d-99c4-78d956fb0330",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "always says hes grinding but has no money",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "2cc1cc0d-d1ed-4929-a641-b07c2327fb14",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he licks the lid clean",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "1e96f7e4-3377-4900-83c2-1d6446879275",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he has bleached hair",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "eeb500eb-87fb-46df-9eaf-d60b3d175111",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he plays wii sports ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "6b3128ee-02b2-439c-aae2-15947b8ae6c7",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he cat calls",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "5a778b0d-5c5f-4c94-9bd5-18f0a201c02e",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he likes trump",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "a7868c7a-dca8-4d1c-b154-250c9e092218",
    game: "dumpable_offense",
    pack: "girlsnight",
    prompt: "he uses 3 in 1 body wash shampoo conditioner",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "e1861745-b39a-4174-9b20-c1911b6a17a2",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who has the hottest dad",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "701fd74e-1b0b-4fb7-bc6b-97e447a4d199",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: 'tell someone to "suck my dick" ',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "34d21fcb-001c-4241-b1d1-6eb10416986a",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "be involved in baby daddy drama ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted",
    sipFlag: 1.0,
  },
  {
    uuid: "9cb09ba5-fdd1-4acc-87bf-5e5563d82fc5",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who has the hottest brother",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "76cd9c92-a060-41b7-9e05-2d307773f640",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who has the least clothing in their tinder pics",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "c2f59a23-4835-4f76-909a-6a3eb7a7b02e",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "has slept wtih the most people",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "73506e77-6229-4695-9f16-b936057e2caa",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who has the most guys in their DMs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "fa46a6dd-cb88-4ac4-b4fa-065137ebea69",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "could give the best lap dance, lets see it",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "ef4fd580-1585-445c-be15-d6422316a263",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who could get the most free drinks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "dcdfad55-1469-4f4a-83da-4b76afc5dd37",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "cant keep a secret",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "c9606d7f-b20f-41f4-ae76-f286c6354911",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "end up on love is blind",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "437e6bd7-49df-4b52-9792-df2b6ac4700f",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: 'have a "guy best friend" who really just a backup plan',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "ee4db3a7-9a7c-40a7-8e04-241b19e2ee89",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "has the best body",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "43a4e3d4-1277-4656-8be4-4e8a78e82531",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get compliment on their butt biggest butt",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "3f31a8bf-a2cb-4c52-9bed-85007f2b3613",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "most likey to get out a speeding ticket by flirting",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "2fea9a89-e47f-4504-ae04-13f8f10c327a",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "end up as a tarot reader",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "1e5ea2a5-2bf7-40f2-8619-5194a074418c",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "who has the best pErsOnalTy",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "3db7ac5d-7341-4644-83a1-977d6afee446",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "tell you about their latest fad diet",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f8663966-7467-47c7-a0c4-d501168171dc",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get complimented on their smile",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f6b87033-0a2e-4db1-8ad8-7ae5f4fd68fe",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "have a roast beef vagina",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "6a522375-f6f6-486e-bc27-8c229f4ebc0b",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "had period sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "19bb6e61-b492-43a3-8cf3-8a010884d833",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "swallow",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "0bbbe6bf-9502-4ad3-be99-b982fca7b877",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "have a one night stand",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "6fcec2e2-18a7-4245-8a52-94e6eca646dc",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "accidently like thei ex's photo while stalkign them",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "094947ca-1911-4d4e-8dac-3e25141f5440",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "break a nail",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "c55ae4c6-9f27-490b-a64f-49c15bd9780e",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "come out of the bathroom with a new best  friend",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "84860c68-7c3a-4bd3-aec6-bb95842a763b",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "be deathly afraid of bugs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f79479e8-7497-470c-a0f1-9d2eafacba45",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "call you to do a man related item",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f1c82c93-d17c-4032-adc6-7512b2445050",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "say they dont need no man",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "ae4ad109-df8c-4cfc-9ee7-e53c0f03732d",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "not be sure who the father is",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "193005cd-7189-4cae-8a90-42a422231db0",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "having a baby daddy",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "091fff58-235c-4fa1-bf82-d383a6440036",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "flirt with the bartender and get free drinks",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "0ff60a3d-6dbe-430e-b593-9f2bd7251cd0",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "pass out at the wine tasting event",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "11ce6da3-0d1b-4cff-b8fa-3efdec640783",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "say I wana do something fun, but then have no reccomendations",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "8be8c8e4-d284-4816-95ba-304447236614",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get caught shoplifting",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f370145d-b312-41ae-af4c-0ae1398551fc",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "have the hiccups",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "d94bacf3-324a-4879-9bf0-e3243e3fac18",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "give you a genuine compliment ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "e4478be5-005d-4fa7-b058-6eed1796dbd5",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: 'get "revenge" on their ex',
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "b067c74a-1570-4eca-b727-ebdc1fedc9c8",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "be the best twerker",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "bf629d8d-ea88-47de-8ea4-3c4c477ea926",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get lip filler",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "fc09b222-6f69-4ac4-82ba-6e0b8824c49b",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get  boob job",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "64b7ad3a-ec4e-439d-a0b5-cd608839c33b",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "whiten their teeth",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "4dba2678-6301-43bf-9bef-587899589254",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get with a fuck boy",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "0ac36a44-0d5c-4bad-962a-3db149b2f136",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "goign to be the best cougar",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "1241ac03-52d3-4657-a036-ea73a71cceb4",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "be a gold digger",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "91c463cc-737e-4e5b-a08f-1cdeaec531b1",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "hand craft something for you",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "f7322e76-d0ad-4577-8d15-764806ae8728",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "literally can't even",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "59d9202a-09d1-4849-9def-7f5542338c7e",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "blame anything on your zodiac sign",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "3d7e15a3-2627-4b10-825a-1946491038a5",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "know the most about the kardashains",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "e45472ec-f43f-4ed4-bfc5-9054de410d73",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "get trapped ina revoling door",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "2f02b203-a309-413b-8472-66a450fed32e",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "always be cold",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "b6da7adc-92e6-4d33-b493-40651b7e99d4",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "sleep their way to the top",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "2b1ca1c7-c5a4-4a9e-a7e4-996f273408c2",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "become a cat lady",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "a9da5585-706c-4728-9233-e0a47bf15b8e",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "go vegan but fail in a week",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "b59f0435-159d-4d1a-9e1c-956208947387",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "ask questions about what happens during a movie",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "2b48b520-8d5d-480a-87da-cb6cc9a4f9b8",
    game: "most_likely_to",
    pack: "girlsnight",
    prompt: "name their pet after a kardashian",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "199f3103-c7e8-4bde-bb35-dcbcced34b3f",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "Thrown up during a BJ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "e2025a0d-7dd0-4640-ba7c-70f6625c34aa",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "hooked up with someone for their accent",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "09bf3049-445c-4fc3-ba08-639191c23506",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had sex with a rando while traveling",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "5de136fe-f091-486c-9a48-cf9c3fe42caa",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had sex with three or more people in a week",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "00b598c2-0c6f-403c-b5d5-25626b15a62c",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "made out with 3 people in a night",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "9a489002-ade1-43e5-a62e-97fc19832ccf",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "blown a dude within an hour of meeting",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "ee8b5c0d-6db2-4a98-b790-5736050ec834",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had a brazillian wax",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "da7dec65-b2e3-4b99-af68-7602f52fa0e7",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "fallen asleep during sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "3ba8c18f-2fd8-49f0-82ab-c10c4a580583",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "taken a call or texted during sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "f563a582-9454-4653-9260-5a658c55dec2",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "made a landingstrip",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "fdd2c422-b496-4687-984c-4a368b61dbcb",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "...squirted",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "5dd38edd-3c1e-495f-81f2-5cc2806dd984",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "hooked up with a friends brother",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "f3fe4da7-208f-48ba-bf96-4f5b22baca5e",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had a sugar daddy",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "591e13e1-06b9-49d7-b0b0-8be25809e901",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "gotten paid for sexual activities",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "f4709dba-b5e9-48aa-b7fc-5d3a81b3360a",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had sex with a dad",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "542c93f1-d269-400a-9856-c425411b0f65",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "faked an orgasm",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "8aa6c4b0-f176-4a3c-8a02-5bc0fde47349",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "seen a 8 incher in person",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "1a3253f4-863a-4d0d-9d2e-9fbea1165695",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "lied about going out to my S.O",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "6f618071-e29f-4a8e-a7b6-470645febdb7",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "used a sheewee",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "c50bc7d6-a70b-492f-9709-acefe613eacd",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "denied a guy because of his height",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "2c011d1a-925c-4f54-82c7-080b217375f7",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "denied a guy because of his dick size",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "f3953a31-0df8-4304-9309-fe5f16172a95",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "made a sex tape",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "e5b04152-b917-4e69-842e-3fccda85c3c3",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been tied up in bed",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "12ab55b5-08ec-48d8-8200-650112f74670",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "applied for a reality TV show",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "9fca0273-05c9-4d6a-85cd-2109a4e66116",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been choked during sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "05b57098-12f7-40bd-b745-ac46df258e0c",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "done the walk on shame",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "adc8aebe-5ccc-415b-9903-e49d7849f468",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "hooked up with over half of a friend group",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "ed6c2f0b-11bb-4e2a-96e9-866a6c5a4826",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "stuffed my bra",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "01c2f4bd-d051-4abd-8d0f-52acf15c97ce",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had to deny a guy because of his breath",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "0d225aca-0e42-4e93-9280-fb93459f5f5f",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "done anal",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "9ebc29c4-4f2a-4a22-9256-c140c86fc6f8",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had sex and wasnt sure if he was inside already",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "6b7ad646-08ec-4143-b17b-af7744613e19",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "made out with another girl",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "f2bb4d6d-04d2-48c7-9f18-cda0562268ca",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "watched 2 girls 1 cup",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "96c98fb9-3681-4848-857c-28daa40f8c39",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been complimented on my voice",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "385b766f-0e90-49b9-86e5-7f81abc26f6a",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "given road dome",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "bffa4993-56ee-4e30-9cef-dbfeef1b6a0e",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had a nip slip at a horrible time",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "1e2d7988-a840-4b8a-aa82-289c4a23ce9c",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had an alphetized spice rack",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "b4c85e6a-4580-4eb7-847c-5076f9526aad",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been obsessed wtih how i look in pictures",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "7feb6343-f02b-49e0-9bbb-3280c537481d",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "convinced a friend to dump their s.o",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "587f3fa8-110a-43d1-b172-d97dfb6f219a",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "thought a reinds baby was ugly",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "a30cddc3-8cc4-4f47-8aa7-6950518532bc",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had a hand fetish",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "df15f1ae-da50-49cc-b506-4e46dcdb8405",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "dumped a guy for his friend",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "cfde89cb-027f-469c-8b63-ad035d4291a3",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been called a c***",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "e7f5f7ba-3f93-456e-87cf-31583ba411a9",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been talking to more than 10 guys at the same time",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "5df18789-cb2c-4f22-8078-e66982161a40",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had over 1000 beeline",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "0340a34a-682f-4952-a796-27299fbf1883",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had no bio on tinder",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "9725e219-1ec0-4f88-b686-eaa7c8e7f5e9",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "been catfished",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "0fa8b860-d4d4-467d-92ca-c7a93ba53c80",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: 'been told "you have nice tits"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "b2830ca7-0b01-4ebc-8278-628efdc5a1ca",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: 'been told "you have  a nice ass"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "3d33ea32-587e-44f4-956b-a84dbdb53e46",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "swallowed over a quart of cum in mylifetime",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "af4ac589-8728-4089-a288-4e3ec0f304c8",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "taken so long to get ready that we missed the event",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "1e0455f5-829a-45fc-b754-09aa61a75c34",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "gone to a tailgate without knowing which sport it's for",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "0214de5a-4f25-44ce-9c6a-c0c86c9263a8",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "forgotten i wasn't wearing underwear and flashed someone",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "a7f7133f-d27c-449d-91d0-15916d157f7b",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "not taken off my mask at all between nights",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "e2afa2aa-ee57-4047-b63f-7cd3edab05ce",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "gone through more than 10 pads in a day",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "07662eda-f8b4-46d0-b824-e1016a2206a9",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "lost a pad in a pool",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "25b6101f-410b-453e-9def-54f976c9ad7c",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: 'gone a month without shaving my legs"',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "affdddf8-5613-41b8-aee2-c74daad7b7b1",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "had long ass armpit hair",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "0b51ed87-add6-46d9-b4b9-b6132e7627c5",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: "shaved my partner",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "68e3ba10-4933-4b3d-8e87-8f4ce7522b54",
    game: "never_have_i_ever",
    pack: "girlsnight",
    prompt: 'taken a "souvenir" from a one night stand',
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "c7cb4c17-0523-410e-a4ea-7c9dfe81bbbe",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "arms or abs",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "cc313774-190d-40d5-9403-f920f0f544be",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "iced or hot coffee",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "fb086360-f516-43dd-aff4-7b063520df72",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "cancun or miami",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "4dc0ffe7-503f-4977-bcfc-48acf1372225",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "break a toe nail or finger nail",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "f52171f3-46fd-4d73-9abf-6c929de66866",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "the rock or jason mamoa",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "5f2de3e7-08bb-4bff-81cb-2acb7e435a45",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "bald & rich or beautiful hair & poor",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "f342733e-bd38-40de-8814-b88bd6b17869",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "caesar salad or house salad",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "53317569-f9cb-40d9-a475-557a26255a8d",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "full beard or clean shave",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "d5c447fd-0e71-47db-952c-2f9b71ba0c8f",
    game: "this_or_that",
    pack: "girlsnight",
    prompt: "military man or EntRepruerr ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority,",
    sipFlag: 1.0,
  },
  {
    uuid: "fea776b4-6ef2-4bd4-a748-d1d6e4e0760a",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "everyone wearing mascara",
    header: "Eye Check",
    cardType: "GROUP",
    drinkHeader: "if you are,",
    sipFlag: 1.0,
  },
  {
    uuid: "b0ee0b4c-92ab-48ed-84b3-e83d72b45334",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "whoever has the shortest boyfriend",
    header: "Short King Owner",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "476ad67c-ab42-41c4-b996-9aab08c485ae",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "would you jerk off a horse for 5k",
    header: "Horse Girl",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1.0,
  },
  {
    uuid: "fc6a5c8a-3fea-4d1f-8140-2d4fc224f50f",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who has recently changed their hair style",
    header: "salon",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1.0,
  },
  {
    uuid: "be7b622e-c1d0-44b0-9b19-ba25c21ccad0",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "words that rhyme with tampon",
    header: "rhyme",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "c092e2cf-8978-463b-a5f0-64fd1848dfd2",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who has used a sex swing",
    header: "weeee",
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1.0,
  },
  {
    uuid: "18e297ae-1251-495d-9fa7-3a368774111f",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who has considered being a stripper",
    header: "$$$",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1.0,
  },
  {
    uuid: "3f88958f-be71-4f1f-a1a9-d62fd8c9afb2",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who has considered making an only fans",
    header: "Get a job",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1.0,
  },
  {
    uuid: "445e1cb2-eeb3-406b-b71d-d381193e35b1",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "everyone who has a bush right now",
    header: "old skool",
    cardType: "GROUP",
    drinkHeader: "if you do,",
    sipFlag: 1.0,
  },
  {
    uuid: "22e97427-cc26-4266-abf7-1c4bfe6324f9",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who would give up chocolate forever for 20k",
    header: "choc addict",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1.0,
  },
  {
    uuid: "b200de18-f021-4365-8e10-5d3545265970",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "faked an orgasm this year?",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "for each one,",
    sipFlag: 1.0,
  },
  {
    uuid: "4d4852b2-3ecc-42d1-90c3-37aafcd079fc",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "Eveyone put your phone in the center",
    header: "Busy Bee",
    cardType: "GROUP",
    drinkHeader: "first notified",
    sipFlag: 1.0,
  },
  {
    uuid: "728e2b46-ebc4-4005-967a-24603d021b49",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "call out anyone with any messed up makeup",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the chosen,",
    sipFlag: 1.0,
  },
  {
    uuid: "5a6ef3e5-7bf9-4246-baf3-de17b92ed8bd",
    game: "wildcard",
    pack: "girlsnight",
    prompt:
      "your bill is $125 and you want to leave a 20% tip, how much is it?",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "get it right,",
    sipFlag: -1.0,
  },
  {
    uuid: "83ad6878-0d66-4556-ab8c-97e6a66b615a",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "call out anyone with any messed up makeup",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the chosen,",
    sipFlag: 1.0,
  },
  {
    uuid: "26414db7-5ec1-4245-b1db-7f81880eb88d",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "if a car drives at 60mph for an hour, how far will it go",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "get it right,",
    sipFlag: -1.0,
  },
  {
    uuid: "e3d30cd6-418a-4ed6-aa9d-f0d23f6002c9",
    game: "wildcard",
    pack: "girlsnight",
    prompt: 'define a "scrotum" to the group',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "they decide if,",
    sipFlag: 1.0,
  },
  {
    uuid: "f37de772-ae91-462d-b392-b2e039900beb",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "who would make the most on feet finder",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "make them,",
    sipFlag: 1.0,
  },
  {
    uuid: "33ef91c4-a076-4fc6-8e54-83cdf02c0346",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "let the player to your left inspect you for brusies",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "find any and,",
    sipFlag: 1.0,
  },
  {
    uuid: "60fdbc40-540d-4bfb-a94b-d6cc4d71c9d1",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "if you cried in the last week ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "0622c5b2-d1d9-4e81-bd7e-bf7f59ed5930",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "if you had a narcassitic ex ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "6fdd7f5c-b1b5-45de-813b-eb9891da3f2a",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "whoever is going to end up a karen",
    header: "KAREN",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1.0,
  },
  {
    uuid: "13be03ad-57d0-479e-92f2-3d5c950788e8",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "everyone who has run out of gas",
    header: "dad...help",
    cardType: "GROUP",
    drinkHeader: "the irresponsible,",
    sipFlag: null,
  },
  {
    uuid: "40b59795-7180-462a-bd45-d075fe61a6a0",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "whoever has more tinder matches",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1.0,
  },
  {
    uuid: "5a8e4b8f-58fa-4fbf-98cd-9bcbb82a7d35",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "whoever has longer hair",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the shortie",
    sipFlag: 1.0,
  },
  {
    uuid: "576e2aaf-7823-4f77-a61b-fcbe848585f6",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone with the same zodiac sign as you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "2e560869-0950-4830-b57a-add9390744ae",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "whoever has better looking nails, group vote",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1.0,
  },
  {
    uuid: "e62c0414-96c6-4a8c-9591-8724c88e6eb5",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "anyone who has seen Drakes dick",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1.0,
  },
  {
    uuid: "1458675a-9277-4dc0-8acb-a82c11bfd609",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "first to get a dick pic send to them",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the fastest,",
    sipFlag: -1.0,
  },
  {
    uuid: "640736ee-2ac7-4fdf-8359-706cbc57acd5",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "give us your best orgasm sound",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1.0,
  },
  {
    uuid: "4c5dc116-154e-4e8f-ab33-30106907249c",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "name 4 kardashians in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1.0,
  },
  {
    uuid: "41649b78-87ea-4f5b-8059-6f6eac762f9b",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "everyone who has held your hair while you puke",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the helpful",
    sipFlag: 1.0,
  },
];
