export default [
  {
    uuid: "0033fba9-8be2-4ef5-b23d-bfdc26997368",
    game: "wildcard",
    pack: "pregame",
    prompt: "what light comes after a red light",
    header: "sciences",
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "036d9401-cf9e-4610-ac23-a05f8df60e37",
    game: "categories",
    pack: "pregame",
    prompt: "netlix shows",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "0b8799c0-1dd7-49e0-be52-cebcec94a563",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "be in the guinessbook of world records",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "0c3f3942-e94a-4291-8567-efddcfa67715",
    game: "categories",
    pack: "pregame",
    prompt: "synonyms for having sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "0ccac64a-b533-4ea2-9ef3-3008d058293c",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone reveal your middle name",
    header: "haha",
    cardType: "GROUP",
    drinkHeader: "the funniest,",
    sipFlag: 1,
  },
  {
    uuid: "0ce42d2f-e157-40d1-89a6-8ae6b614eb79",
    game: "this_or_that",
    pack: "pregame",
    prompt: "rhinna or beyonce",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "0d190ed2-33f1-4446-94f1-c9753bcc5018",
    game: "wildcard",
    pack: "pregame",
    prompt: "hand slapping contest",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "0e83e29e-052c-4206-a123-abdabe5c56b2",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you have swamp ass",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "0e958afb-cf3f-4490-b688-5d4b2607ac59",
    game: "wildcard",
    pack: "pregame",
    prompt: 'whoever has slept with  a "bestfriend"',
    header: "mhm",
    cardType: "GROUP",
    drinkHeader: "the liars,",
    sipFlag: 1,
  },
  {
    uuid: "0efcbb19-563b-4daa-b31e-ee512c9de9d7",
    game: "categories",
    pack: "pregame",
    prompt: "synonyms for masterbaiting",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "101589de-aa92-4508-bd3a-3548a541ae41",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been caught masterbaiting",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "107af047-cbe3-45ca-b2ba-8597ce33fc16",
    game: "categories",
    pack: "pregame",
    prompt: "ways to die",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "11d25374-a03e-4b9e-8760-8570c00146de",
    game: "this_or_that",
    pack: "pregame",
    prompt: "flip cup or slap cup",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "14b2af2d-d144-4a6b-bcd3-7253b3ed55dc",
    game: "wildcard",
    pack: "pregame",
    prompt: "vote on who would look best as the opposite gender",
    header: "hello there",
    cardType: "GROUP",
    drinkHeader: "the chosen,",
    sipFlag: 1,
  },
  {
    uuid: "169a2708-eda9-4163-a38d-3eca8916dd42",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "let the group see your amazon order history",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "1b0cb21e-9170-418e-b299-9370fd20997f",
    game: "wildcard",
    pack: "pregame",
    prompt: "go back and forth naming ice cream toppings",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "1d44c516-ac7f-421c-a496-42540e364ccf",
    game: "this_or_that",
    pack: "pregame",
    prompt: "only be able to shout or whisper",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "2159b087-72d1-4296-8178-ed02d24b83e6",
    game: "this_or_that",
    pack: "pregame",
    prompt: "boof a shot of everclear-drink a shot of piss",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "23677be5-d44e-4276-8cf0-b8c558dd765f",
    game: "wildcard",
    pack: "pregame",
    prompt: "go in a circle saying each letter of the alphabet backwards",
    header: "tebahpla",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "23688ac4-40e4-44cc-a6a5-0a9750379e65",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "say kobe and airball",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "23f8b8dd-4462-41d3-8e68-09d6f9dd0d28",
    game: "wildcard",
    pack: "pregame",
    prompt: "the person you've known the longest",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "and you,",
    sipFlag: 1,
  },
  {
    uuid: "24b05dca-be90-4239-9ddd-a29830341a56",
    game: "categories",
    pack: "pregame",
    prompt: "stripper names",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "24f1cd69-5216-4657-a147-6e6a8f5446d6",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "sent a stranger a drink",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2556b24e-28c0-436f-aca2-5c23952af639",
    game: "wildcard",
    pack: "pregame",
    prompt: "dance off",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "28badcd6-80fb-4ef4-8c62-5e245889746d",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "let the person to your left draw a penis on your arm",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "28f90834-f4aa-4d45-82a3-a83fdc929a6f",
    game: "this_or_that",
    pack: "pregame",
    prompt: "always be stuck in traffic or have bad internet connection",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "291680d9-6211-494a-8511-378f52ef06e2",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "worked at a restaurant",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2b338347-c079-4c2a-b91b-95650d04f4ff",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "get a divorce within a week of marrying",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "2dee21d8-6d06-484e-8601-085a53b7432a",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been drunk in class",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "2f89c78b-1919-447b-b1da-56397e0f9b72",
    game: "wildcard",
    pack: "pregame",
    prompt: "the person on your left and right",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "3125da3b-2f64-4a68-887b-1a2c8a094654",
    game: "categories",
    pack: "pregame",
    prompt: "synonyms for urinating",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "31588bfc-7013-4646-9549-82d0979b8b07",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone whose gotten a promotion this year",
    header: "gud 4 u",
    cardType: "GROUP",
    drinkHeader: "congrats,",
    sipFlag: 1,
  },
  {
    uuid: "326036ec-184a-455a-9370-c730f035fd4a",
    game: "wildcard",
    pack: "pregame",
    prompt:
      "if a train leaves on Monday, travels for a day, loops back Saturday and then ends up where it started. When did it leave?",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "get it and,",
    sipFlag: -1,
  },
  {
    uuid: "33d03bca-9c29-42f5-9d1c-c725d643b226",
    game: "wildcard",
    pack: "pregame",
    prompt: "if its 14:47 in New York, what time is it in California",
    header: "timezones",
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "33df15b5-ffab-4db1-8790-856de5f7053b",
    game: "categories",
    pack: "pregame",
    prompt: "types of chinese foods",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "341436a3-7237-4ea8-90fa-f6c0b2a78470",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who has lived with me",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "35067f4c-a577-4550-a4c3-212041310498",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "do a shot ski",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "38ab3cd0-20a7-46e2-9361-e45da3f9d6b9",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone who has taken or bought a plan-B pill",
    header: "life saveer",
    cardType: "GROUP",
    drinkHeader: "the unwrapped,",
    sipFlag: 1,
  },
  {
    uuid: "38b5d899-188d-479c-a68a-f73a7658f3a1",
    game: "wildcard",
    pack: "pregame",
    prompt: "your bill is $305.50 how much is a 20% tip",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "3a2c1148-f49f-4c59-80c7-2ae67eb863b1",
    game: "this_or_that",
    pack: "pregame",
    prompt: "shotgun or take a shot",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "3a9a3c99-5513-4721-9459-8c0c6969ad20",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "be late for their own wedding",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "3ad4fed5-95a9-46fe-a945-a8a54e162ac1",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "point to who you think is best in bed",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "3ec57e1b-00dd-4364-afd2-cca7656b3cd0",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "buy oregano thinking it was weed",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "41bf433a-1beb-460a-b302-b807431076d0",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "had a threesome",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "4831359a-1f71-42af-baa2-151f811d0d99",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who would rub ghost peppers on their junk for 10k",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "48cffb14-2b33-4384-93c1-a42e40a4fbce",
    game: "this_or_that",
    pack: "pregame",
    prompt: "margarita or moscow mule",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4901c7ad-8e61-4eef-adb6-1a7983c63102",
    game: "wildcard",
    pack: "pregame",
    prompt: "brunettes",
    header: null,
    cardType: "GROUP",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "4c267773-77a8-4f4d-b627-81cc086ea9ed",
    game: "this_or_that",
    pack: "pregame",
    prompt: "meet your future self or future kids",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4d7f036a-cb80-4b75-b081-ed6a7179a64d",
    game: "this_or_that",
    pack: "pregame",
    prompt: "white teeth & bad breath or minty breath & gross teeth",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "4e37eb51-7b65-4ecc-9a2a-a7bb1871d6af",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "dropped acid",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "50d9fb7c-797f-4984-bf62-421826528d78",
    game: "wildcard",
    pack: "pregame",
    prompt: "how much is 3 quarters,4 dimes, 1 nickle and 2 pennies",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "541e1488-c31d-4b09-acc5-314263067fae",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "tell each player how they will die",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "5a05fa3e-7eeb-4fbe-8e26-dd8771c7b542",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "role played in the bedroom",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "5a7c842a-2793-49e6-a2ea-1369df9cee04",
    game: "wildcard",
    pack: "pregame",
    prompt: "last player still touching the floor",
    header: "LAVA",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "5c54e6b4-c303-4941-b586-12e289023579",
    game: "do_or_drink",
    pack: "pregame",
    prompt:
      "nose touch and maintain eyecontact with the player to your left for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 3,
  },
  {
    uuid: "5c83a75e-12be-4b07-9319-493d9a62364c",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who went to school with you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "5cc9f009-8c10-425e-8caa-68cdc037034e",
    game: "this_or_that",
    pack: "pregame",
    prompt: "sleep with the tv on or sleep with white noise",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "60e8d293-7750-45a8-85c7-d911210735f4",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been an ipad kid",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "6273af9e-9fa1-4ffc-9d1e-085d58c4a16f",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you are straight",
    header: "straight!",
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "628ff161-0a11-4873-869e-bb8e0389f3f6",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "bring a knife to a gun fight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "638f33a8-7097-406a-a87d-e684ed4b9892",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone stand on one leg",
    header: "legz",
    cardType: "GROUP",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "63c23d6d-8580-4f71-ac96-61913969bcdb",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "smashed someones pumpkins ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "63f65f72-4c01-43df-911a-55d63f83878d",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who would eat a hanful of live wasps for 50k",
    header: "would u now",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: -1,
  },
  {
    uuid: "65d7b6d3-f26a-4628-bb23-a9186a4a87c0",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "done an enema ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "6a3edc35-d2bb-4d36-84a2-ca489513e7f7",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "sent or recieved over 10 dick pics",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "6ac7b30b-68a7-4571-902a-5f598a5c78d9",
    game: "wildcard",
    pack: "pregame",
    prompt: "Anyone with a drink in hand",
    header: "Gotcha",
    cardType: "GROUP",
    drinkHeader: "if you do,",
    sipFlag: 1,
  },
  {
    uuid: "6b1c334b-28ac-4023-ad2d-681e794ec5b5",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "done a juice cleanse",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "6be3c3dd-439e-498b-a2c5-3ba64bcaaa8a",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "join a gang",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "6c653a35-3bde-45a0-a49b-86758a799cf8",
    game: "wildcard",
    pack: "pregame",
    prompt: "whoever has drank the most",
    header: "drunkie",
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "6e073238-5924-476f-8796-49c9374b6c16",
    game: "wildcard",
    pack: "pregame",
    prompt: "the person you've known the least amount of time",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "and you,",
    sipFlag: 1,
  },
  {
    uuid: "6e166d6d-d525-4aab-b3f1-46441daaa418",
    game: "wildcard",
    pack: "pregame",
    prompt: "for every person here who shares your gender",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: -1,
  },
  {
    uuid: "6eafd370-4f91-4a32-bbeb-3f00cd35cd46",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone younger than you ",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "6f47506d-7443-4546-ac0c-c11d1c48a2f5",
    game: "wildcard",
    pack: "pregame",
    prompt: "on the count of 3, everyone use your hand to show a number",
    header: null,
    cardType: "GROUP",
    drinkHeader: "any matches,",
    sipFlag: 1,
  },
  {
    uuid: "6fb1ffe3-b184-4f90-8c0d-636784998109",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone whose favorite sex position is doggy style",
    header: "woof woof",
    cardType: "GROUP",
    drinkHeader: "the dogs,",
    sipFlag: 1,
  },
  {
    uuid: "735a7111-a385-4664-b00b-ef6c8733a20f",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "fallen asleep on the toilet",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "761e8119-a4bc-42dc-ba2c-4285f65c012b",
    game: "wildcard",
    pack: "pregame",
    prompt: 'solve for x "12x+3=15"',
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "77559434-aa52-4e95-b608-90eea4493d96",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "sit on the lap of the person to your right until your next turn",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "77fad98f-ac3d-46c9-9824-b0e119d6a3ea",
    game: "wildcard",
    pack: "pregame",
    prompt:
      "put your shoes on your hands and take a sip, if you succed the group drinks",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "78a1b6d1-fc1b-4da3-8073-13720b6832ba",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "boofed (butt chuggle)",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "7a16cc70-cf7c-450d-b1f3-4d8f04dac023",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "made weed brownies",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "7b7f5f25-2a35-479b-b450-9a19c94ac423",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "marry a drug lord",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "80539f0d-3dab-4bd9-ab77-9054e71f5ee9",
    game: "wildcard",
    pack: "pregame",
    prompt: "smell the breath of the person to your right",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and,",
    sipFlag: 1,
  },
  {
    uuid: "80f61619-0df8-4261-8b6b-2899905a9b0e",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "built a snowman",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "819d5f90-75c9-4fb1-8360-5483db05707f",
    game: "categories",
    pack: "pregame",
    prompt: "synonyms for weed",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "8362ed2e-8045-45e0-81d6-a9e368f3cdf1",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "compliment everyone here",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "862461a6-3ebe-49ad-bfd7-901976afde32",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "try and rob a gas stration",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "87189582-0f02-4c60-8c04-91c3c45da2ce",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "had a hairy butthole",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "88de761a-6ed1-4a10-b39b-bcb54b9ed11c",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "start an internet fight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "88ff84fb-845e-44c3-85ed-e0af7015f2e0",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "become a nun",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "8a44abad-60d9-42fb-b847-439cd7b57b07",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "be awkard on the first date",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "8c7e24c0-c8d4-4f38-acd7-bb055183e260",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "let the group go through your pics",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "8e1b37a6-c491-451b-802c-099c5a4e84ba",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you have any vowels in your initials drink",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the winner",
    sipFlag: -1,
  },
  {
    uuid: "8f9a05a8-62d8-42aa-a63c-40123a8fd585",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "give the player to your right a foot massage for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "8fe40ee5-ef77-40cd-b414-0ab2230b60f5",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "buy a sex robot",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "911b45e3-6a27-43a8-9a16-20488d455986",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who would give up chocolate forever for 20k",
    header: "choc addict",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "9201dab0-3bde-4969-8e0c-c52bbcc948b6",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who has taken a pic of their shit",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if so,",
    sipFlag: -1,
  },
  {
    uuid: "928f918d-fa5f-4977-b5f8-ec9b0be35cb1",
    game: "wildcard",
    pack: "pregame",
    prompt: "take a sip out of everyones drink",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "else,",
    sipFlag: 1,
  },
  {
    uuid: "94242c6d-d366-4eda-94fc-7c4a29d18c06",
    game: "this_or_that",
    pack: "pregame",
    prompt: "know how you die or when you die",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "98574ea5-9553-45a4-a65c-47ed97836e45",
    game: "wildcard",
    pack: "pregame",
    prompt: "last person to put their elbow on the ground",
    header: "down",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "9ee7fb20-3843-40f5-ae5f-1046160ddc54",
    game: "wildcard",
    pack: "pregame",
    prompt:
      "turn into a human table, and let someone put a beer on you until your next turn",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "succeed and,",
    sipFlag: -1,
  },
  {
    uuid: "9f06d7cd-c3ec-4496-85d5-fe86121c04bc",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone with a cracked phone screen",
    header: "new phone who dis",
    cardType: "GROUP",
    drinkHeader: "the cracks,",
    sipFlag: 1,
  },
  {
    uuid: "a2d1d1a3-1761-4085-8587-cc90b3dba61c",
    game: "wildcard",
    pack: "pregame",
    prompt: "give us your best joke",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "no laughs,",
    sipFlag: 1,
  },
  {
    uuid: "a6e91b20-2838-4384-bbb9-1bbba6a6e59a",
    game: "wildcard",
    pack: "pregame",
    prompt: "name a location you've been to",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you've been,",
    sipFlag: 1,
  },
  {
    uuid: "aa8c2bd9-7e55-427e-a6cc-207dd42e23b9",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you've hooked up with a co-worker",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "abf281ce-fb78-445c-8409-bde6b8d25d98",
    game: "wildcard",
    pack: "pregame",
    prompt: "whoever has drank the least",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the accused",
    sipFlag: 1,
  },
  {
    uuid: "ac23c80d-bd0a-48da-a67d-f4dbb9d8bece",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "eat something off the floor",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "acd3e003-170b-4fdc-9090-3358f6c1d6c9",
    game: "this_or_that",
    pack: "pregame",
    prompt: "house party or bar",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "ace8e723-8beb-46ad-b555-1ea185fa26ba",
    game: "this_or_that",
    pack: "pregame",
    prompt: "xbox or playstation",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "b620c131-cd8b-4e96-bd5e-9df6c2b3fd7f",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "let the person to your left slap you in the face",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or both",
    sipFlag: 2,
  },
  {
    uuid: "b6304ce4-67db-4bb0-ad5d-6b6827100024",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "mooned someone",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "b7fc52cd-5c2e-462c-a8a6-9ee34289d14d",
    game: "wildcard",
    pack: "pregame",
    prompt: "are you a vandal?",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if so,",
    sipFlag: 1,
  },
  {
    uuid: "b81ad9b6-2b13-416d-9d08-3b303c666bd9",
    game: "do_or_drink",
    pack: "pregame",
    prompt: 'text back the last person you left on "read" now',
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "b8e0b65f-41c2-4096-b180-b24bedc13ec0",
    game: "wildcard",
    pack: "girlsnight",
    prompt: "for each shot you've taken today",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "b9318003-f051-41bb-97ba-a01b049c6035",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "thrown up directly after a shot",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "baf54462-2abb-423e-89d7-7b2242472286",
    game: "wildcard",
    pack: "pregame",
    prompt: "wall-sit competition ",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the winner,",
    sipFlag: -1,
  },
  {
    uuid: "bcc0e8f2-1528-462b-9ad1-7b1cdd9423ca",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "get detained for harrasing a policeman",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "befb4936-797a-4266-8a22-882c5886702e",
    game: "categories",
    pack: "pregame",
    prompt: "things people say during sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "c0085e5f-1675-419d-bca1-8387aaa11550",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "win the lottery and lose the ticket",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "c0c00455-a3cb-4d19-a01a-197986e928d1",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "be a fbi agent",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "c0e45d55-05d3-465a-ba31-7ecfe5b9321d",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "eat someone elses food",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "c13d9fda-609e-4fa1-8b60-86a4fef8c0a2",
    game: "wildcard",
    pack: "pregame",
    prompt: "everyone give us your best fart noise",
    header: "toot",
    cardType: "GROUP",
    drinkHeader: "the best,",
    sipFlag: -1,
  },
  {
    uuid: "c44915c4-c122-4197-b723-c93f32abe7d4",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone shorter than you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "c6166389-e934-45d6-bcc1-8a4caf720129",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "lick their plate after a meal",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "c6583d52-b5e8-4853-b180-6e224a9a617e",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "help you hide a dead body",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "c670ac1f-c07d-4504-87c4-9c67bc447081",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "had to wipe with something other than tp",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "c9d462b5-2722-4e16-9112-17968d190f95",
    game: "this_or_that",
    pack: "pregame",
    prompt: "have your face on the $1 or $100 bill",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "c9d931fd-ba80-4abf-9a48-4ddcb2609499",
    game: "wildcard",
    pack: "pregame",
    prompt: "correctly say everyones name",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "cc2e6179-6f65-4f02-8125-092bcf01e26c",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "sort the group dumbest to smartest",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "cdcbafde-7977-4c5a-882e-78b633bb1946",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "have an affair",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "cf3bb2bf-c862-4035-b83b-533bc18bd981",
    game: "wildcard",
    pack: "pregame",
    prompt: "choose 2 other players and make a human pyramid",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "succeed and,",
    sipFlag: -1,
  },
  {
    uuid: "d1e8c92e-eaf7-4e66-95c9-0880bbf94f04",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone who has sold drugs",
    header: "arms of an angel",
    cardType: "GROUP",
    drinkHeader: "if so,",
    sipFlag: -1,
  },
  {
    uuid: "d3a3887b-6803-471e-a78f-61f722eb7eb2",
    game: "wildcard",
    pack: "pregame",
    prompt: "pose like a flamingo and hold it for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "d471bf16-17a5-489f-8398-0377dd939d98",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "sing and dance the YMCA for 30 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 2,
  },
  {
    uuid: "d6998ad5-7069-4a72-829f-d5113036b726",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "broken up via text",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "d7a59cae-2296-4b27-bc09-273f1da1284a",
    game: "wildcard",
    pack: "pregame",
    prompt: "trust fall into the group",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "do it and",
    sipFlag: -1,
  },
  {
    uuid: "d7cb23a0-44fb-4b06-9a21-c2726798f8b4",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "laugh during a serious moment",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "dbf606b8-8fba-416e-8a7a-4be6c61facd5",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you are not straight",
    header: "!straight",
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "df870e7f-bb11-44f7-84cf-1ccb419dae32",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone taller than you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "e01136e5-706a-43f5-9123-97be05d17150",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "done a keg stand",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "e08be01c-ae66-4622-b56e-9f96fee23e50",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "be addicted to social media",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "e68ec0f2-d456-41b2-82d6-1d0cad825806",
    game: "wildcard",
    pack: "pregame",
    prompt:
      "fill your mouth with liquid - the group has 10 seconds to make you laugh",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you do,",
    sipFlag: 1,
  },
  {
    uuid: "e965db4c-0697-49e1-b6d7-1201e244f491",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "name 3 sex positions in 10 seconds",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "ea3bfa5a-4aec-41d7-ba6f-c0185ea3bbf4",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "slept with a friends ex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "ea84f393-2a82-4139-945b-2fbbd6510a9f",
    game: "wildcard",
    pack: "pregame",
    prompt: "spell your entire name backwards",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "lose and,",
    sipFlag: 1,
  },
  {
    uuid: "eae590c3-fbc9-4704-924a-616cbaa3f02d",
    game: "wildcard",
    pack: "pregame",
    prompt: "last person to raise their hand",
    header: "up",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "eb1a11ea-89e4-42ac-bb02-5201ed926e30",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been on the radio",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "eb885a31-fa33-4583-ad51-525a90dcb732",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "walk into a glass door",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "ecc3c69f-064e-4509-b8d6-e349df00fb23",
    game: "wildcard",
    pack: "pregame",
    prompt: "if you have G,T,K,L,P,R or S in your initials",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "ee548862-6803-4a27-b6a5-ff3ebece2b02",
    game: "wildcard",
    pack: "pregame",
    prompt:
      "everyone look down, on the count of 3 - look up and stare at someone.",
    header: "medusa",
    cardType: "GROUP",
    drinkHeader: "lock eyes and both",
    sipFlag: 1,
  },
  {
    uuid: "f0ace2b2-30b8-4b8e-a017-9ed282e9f08e",
    game: "wildcard",
    pack: "pregame",
    prompt: "whoever sleeps naked",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "the noods,",
    sipFlag: 1,
  },
  {
    uuid: "f1dc8898-102a-4e62-99d0-d693cdd8d5ca",
    game: "wildcard",
    pack: "pregame",
    prompt: "explain potential vs kinetic energy to the group",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "group votes,",
    sipFlag: 1,
  },
  {
    uuid: "f1dd9c9d-ac09-47ae-a1b9-d70acd5a0866",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "have gone to a gay club",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "f1eb1d4b-6cf2-4bcf-89c9-2f12f639c977",
    game: "wildcard",
    pack: "pregame",
    prompt: "guess everyones age",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "if you fail,",
    sipFlag: 1,
  },
  {
    uuid: "f22d8b41-60b4-4e30-a12c-8924532ca697",
    game: "do_or_drink",
    pack: "pregame",
    prompt:
      "let the group pick someone on your snapchat and say whatever they want",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 3,
  },
  {
    uuid: "f2a44ef7-c943-4503-aa1c-0d33eb9563ec",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "help you with a cover story ",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "f311527b-a334-4d71-b324-6e978e876d3a",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been injured during sex",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f37bc580-b32a-45a5-9037-8d2d7cc51bb0",
    game: "most_likely_to",
    pack: "pregame",
    prompt: "end up with their phone ina bag of rice tonight",
    header: null,
    cardType: "GROUP",
    drinkHeader: "most voted,",
    sipFlag: 1,
  },
  {
    uuid: "f46ccb8f-6802-4e17-922e-8bde5b3073e7",
    game: "this_or_that",
    pack: "pregame",
    prompt:
      "have your parents be fully open about their sex life or keep it a secret",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "f4aee1e0-c92b-40ea-8a5f-3d51a6daa286",
    game: "wildcard",
    pack: "pregame",
    prompt: "words that rhyme with penis",
    header: "rhyme",
    cardType: "GROUP",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "f5330d90-424a-40da-bd22-ff34b00d160f",
    game: "wildcard",
    pack: "pregame",
    prompt: "anyone older than you",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: null,
    sipFlag: 1,
  },
  {
    uuid: "f6227079-814d-4084-853b-c76879762168",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "scrolled on the toilet so long your legs go numb",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f75d0e16-feb6-43c7-90a1-0e9f5b83a561",
    game: "never_have_i_ever",
    pack: "pregame",
    prompt: "been shit on by a bird",
    header: null,
    cardType: "GROUP",
    drinkHeader: "if you have,",
    sipFlag: 1,
  },
  {
    uuid: "f9ad28d8-a16e-44c6-9b19-5e40c7b268a2",
    game: "wildcard",
    pack: "pregame",
    prompt: "stare off",
    header: null,
    cardType: "HEAD_TO_HEAD",
    drinkHeader: "the loser",
    sipFlag: 1,
  },
  {
    uuid: "fd9764d0-1ad0-4cd7-81f3-eda67a85933e",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "spin in a cirlce 10 times then try and walk in a striaght line",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
  {
    uuid: "fdcd1b14-1880-4e73-a9d0-220bd47296fa",
    game: "this_or_that",
    pack: "pregame",
    prompt: "no sex for 2 years or no phone 2 years",
    header: null,
    cardType: "GROUP",
    drinkHeader: "the minority",
    sipFlag: 1,
  },
  {
    uuid: "fe8316a9-082a-485f-bdcb-d7a4411bde5b",
    game: "wildcard",
    pack: "pregame",
    prompt: "show the room your feet",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "refuse and,",
    sipFlag: 1,
  },
  {
    uuid: "677f9d7a-c7ef-471a-a8fe-028d7b485c80",
    game: "do_or_drink",
    pack: "pregame",
    prompt: "tell us who is most likely to eat a booger",
    header: null,
    cardType: "INDIVIDUAL",
    drinkHeader: "or",
    sipFlag: 1,
  },
];
